#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#include "constants/pokemon_config.h"

#define SPECIES_NONE 0
#define SPECIES_BULBASAUR 1
#define SPECIES_IVYSAUR 2
#define SPECIES_VENUSAUR 3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD 6
#define SPECIES_SQUIRTLE 7
#define SPECIES_WARTORTLE 8
#define SPECIES_BLASTOISE 9
#define SPECIES_CATERPIE 10
#define SPECIES_METAPOD 11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE 13
#define SPECIES_KAKUNA 14
#define SPECIES_BEEDRILL 15
#define SPECIES_PIDGEY 16
#define SPECIES_PIDGEOTTO 17
#define SPECIES_PIDGEOT 18
#define SPECIES_RATTATA 19
#define SPECIES_RATICATE 20
#define SPECIES_SPEAROW 21
#define SPECIES_FEAROW 22
#define SPECIES_EKANS 23
#define SPECIES_ARBOK 24
#define SPECIES_PIKACHU 25
#define SPECIES_RAICHU 26
#define SPECIES_SANDSHREW 27
#define SPECIES_SANDSLASH 28
#define SPECIES_NIDORAN_F 29
#define SPECIES_NIDORINA 30
#define SPECIES_NIDOQUEEN 31
#define SPECIES_NIDORAN_M 32
#define SPECIES_NIDORINO 33
#define SPECIES_NIDOKING 34
#define SPECIES_CLEFAIRY 35
#define SPECIES_CLEFABLE 36
#define SPECIES_VULPIX 37
#define SPECIES_NINETALES 38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT 41
#define SPECIES_GOLBAT 42
#define SPECIES_ODDISH 43
#define SPECIES_GLOOM 44
#define SPECIES_VILEPLUME 45
#define SPECIES_PARAS 46
#define SPECIES_PARASECT 47
#define SPECIES_VENONAT 48
#define SPECIES_VENOMOTH 49
#define SPECIES_DIGLETT 50
#define SPECIES_DUGTRIO 51
#define SPECIES_MEOWTH 52
#define SPECIES_PERSIAN 53
#define SPECIES_PSYDUCK 54
#define SPECIES_GOLDUCK 55
#define SPECIES_MANKEY 56
#define SPECIES_PRIMEAPE 57
#define SPECIES_GROWLITHE 58
#define SPECIES_ARCANINE 59
#define SPECIES_POLIWAG 60
#define SPECIES_POLIWHIRL 61
#define SPECIES_POLIWRATH 62
#define SPECIES_ABRA 63
#define SPECIES_KADABRA 64
#define SPECIES_ALAKAZAM 65
#define SPECIES_MACHOP 66
#define SPECIES_MACHOKE 67
#define SPECIES_MACHAMP 68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL 72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE 74
#define SPECIES_GRAVELER 75
#define SPECIES_GOLEM 76
#define SPECIES_PONYTA 77
#define SPECIES_RAPIDASH 78
#define SPECIES_SLOWPOKE 79
#define SPECIES_SLOWBRO 80
#define SPECIES_MAGNEMITE 81
#define SPECIES_MAGNETON 82
#define SPECIES_FARFETCHD 83
#define SPECIES_DODUO 84
#define SPECIES_DODRIO 85
#define SPECIES_SEEL 86
#define SPECIES_DEWGONG 87
#define SPECIES_GRIMER 88
#define SPECIES_MUK 89
#define SPECIES_SHELLDER 90
#define SPECIES_CLOYSTER 91
#define SPECIES_GASTLY 92
#define SPECIES_HAUNTER 93
#define SPECIES_GENGAR 94
#define SPECIES_ONIX 95
#define SPECIES_DROWZEE 96
#define SPECIES_HYPNO 97
#define SPECIES_KRABBY 98
#define SPECIES_KINGLER 99
#define SPECIES_VOLTORB 100
#define SPECIES_ELECTRODE 101
#define SPECIES_EXEGGCUTE 102
#define SPECIES_EXEGGUTOR 103
#define SPECIES_CUBONE 104
#define SPECIES_MAROWAK 105
#define SPECIES_HITMONLEE 106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG 108
#define SPECIES_KOFFING 109
#define SPECIES_WEEZING 110
#define SPECIES_RHYHORN 111
#define SPECIES_RHYDON 112
#define SPECIES_CHANSEY 113
#define SPECIES_TANGELA 114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA 116
#define SPECIES_SEADRA 117
#define SPECIES_GOLDEEN 118
#define SPECIES_SEAKING 119
#define SPECIES_STARYU 120
#define SPECIES_STARMIE 121
#define SPECIES_MR_MIME 122
#define SPECIES_SCYTHER 123
#define SPECIES_JYNX 124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR 126
#define SPECIES_PINSIR 127
#define SPECIES_TAUROS 128
#define SPECIES_MAGIKARP 129
#define SPECIES_GYARADOS 130
#define SPECIES_LAPRAS 131
#define SPECIES_DITTO 132
#define SPECIES_EEVEE 133
#define SPECIES_VAPOREON 134
#define SPECIES_JOLTEON 135
#define SPECIES_FLAREON 136
#define SPECIES_PORYGON 137
#define SPECIES_OMANYTE 138
#define SPECIES_OMASTAR 139
#define SPECIES_KABUTO 140
#define SPECIES_KABUTOPS 141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX 143
#define SPECIES_ARTICUNO 144
#define SPECIES_ZAPDOS 145
#define SPECIES_MOLTRES 146
#define SPECIES_DRATINI 147
#define SPECIES_DRAGONAIR 148
#define SPECIES_DRAGONITE 149
#define SPECIES_MEWTWO 150
#define SPECIES_MEW 151
#define SPECIES_CHIKORITA 152
#define SPECIES_BAYLEEF 153
#define SPECIES_MEGANIUM 154
#define SPECIES_CYNDAQUIL 155
#define SPECIES_QUILAVA 156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE 158
#define SPECIES_CROCONAW 159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET 161
#define SPECIES_FURRET 162
#define SPECIES_HOOTHOOT 163
#define SPECIES_NOCTOWL 164
#define SPECIES_LEDYBA 165
#define SPECIES_LEDIAN 166
#define SPECIES_SPINARAK 167
#define SPECIES_ARIADOS 168
#define SPECIES_CROBAT 169
#define SPECIES_CHINCHOU 170
#define SPECIES_LANTURN 171
#define SPECIES_PICHU 172
#define SPECIES_CLEFFA 173
#define SPECIES_IGGLYBUFF 174
#define SPECIES_TOGEPI 175
#define SPECIES_TOGETIC 176
#define SPECIES_NATU 177
#define SPECIES_XATU 178
#define SPECIES_MAREEP 179
#define SPECIES_FLAAFFY 180
#define SPECIES_AMPHAROS 181
#define SPECIES_BELLOSSOM 182
#define SPECIES_MARILL 183
#define SPECIES_AZUMARILL 184
#define SPECIES_SUDOWOODO 185
#define SPECIES_POLITOED 186
#define SPECIES_HOPPIP 187
#define SPECIES_SKIPLOOM 188
#define SPECIES_JUMPLUFF 189
#define SPECIES_AIPOM 190
#define SPECIES_SUNKERN 191
#define SPECIES_SUNFLORA 192
#define SPECIES_YANMA 193
#define SPECIES_WOOPER 194
#define SPECIES_QUAGSIRE 195
#define SPECIES_ESPEON 196
#define SPECIES_UMBREON 197
#define SPECIES_MURKROW 198
#define SPECIES_SLOWKING 199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN 201
#define SPECIES_WOBBUFFET 202
#define SPECIES_GIRAFARIG 203
#define SPECIES_PINECO 204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE 206
#define SPECIES_GLIGAR 207
#define SPECIES_STEELIX 208
#define SPECIES_SNUBBULL 209
#define SPECIES_GRANBULL 210
#define SPECIES_QWILFISH 211
#define SPECIES_SCIZOR 212
#define SPECIES_SHUCKLE 213
#define SPECIES_HERACROSS 214
#define SPECIES_SNEASEL 215
#define SPECIES_TEDDIURSA 216
#define SPECIES_URSARING 217
#define SPECIES_SLUGMA 218
#define SPECIES_MAGCARGO 219
#define SPECIES_SWINUB 220
#define SPECIES_PILOSWINE 221
#define SPECIES_CORSOLA 222
#define SPECIES_REMORAID 223
#define SPECIES_OCTILLERY 224
#define SPECIES_DELIBIRD 225
#define SPECIES_MANTINE 226
#define SPECIES_SKARMORY 227
#define SPECIES_HOUNDOUR 228
#define SPECIES_HOUNDOOM 229
#define SPECIES_KINGDRA 230
#define SPECIES_PHANPY 231
#define SPECIES_DONPHAN 232
#define SPECIES_PORYGON2 233
#define SPECIES_STANTLER 234
#define SPECIES_SMEARGLE 235
#define SPECIES_TYROGUE 236
#define SPECIES_HITMONTOP 237
#define SPECIES_SMOOCHUM 238
#define SPECIES_ELEKID 239
#define SPECIES_MAGBY 240
#define SPECIES_MILTANK 241
#define SPECIES_BLISSEY 242
#define SPECIES_RAIKOU 243
#define SPECIES_ENTEI 244
#define SPECIES_SUICUNE 245
#define SPECIES_LARVITAR 246
#define SPECIES_PUPITAR 247
#define SPECIES_TYRANITAR 248
#define SPECIES_LUGIA 249
#define SPECIES_HO_OH 250
#define SPECIES_CELEBI 251
#define SPECIES_TREECKO 252
#define SPECIES_GROVYLE 253
#define SPECIES_SCEPTILE 254
#define SPECIES_TORCHIC 255
#define SPECIES_COMBUSKEN 256
#define SPECIES_BLAZIKEN 257
#define SPECIES_MUDKIP 258
#define SPECIES_MARSHTOMP 259
#define SPECIES_SWAMPERT 260
#define SPECIES_POOCHYENA 261
#define SPECIES_MIGHTYENA 262
#define SPECIES_ZIGZAGOON 263
#define SPECIES_LINOONE 264
#define SPECIES_WURMPLE 265
#define SPECIES_SILCOON 266
#define SPECIES_BEAUTIFLY 267
#define SPECIES_CASCOON 268
#define SPECIES_DUSTOX 269
#define SPECIES_LOTAD 270
#define SPECIES_LOMBRE 271
#define SPECIES_LUDICOLO 272
#define SPECIES_SEEDOT 273
#define SPECIES_NUZLEAF 274
#define SPECIES_SHIFTRY 275
#define SPECIES_TAILLOW 276
#define SPECIES_SWELLOW 277
#define SPECIES_WINGULL 278
#define SPECIES_PELIPPER 279
#define SPECIES_RALTS 280
#define SPECIES_KIRLIA 281
#define SPECIES_GARDEVOIR 282
#define SPECIES_SURSKIT 283
#define SPECIES_MASQUERAIN 284
#define SPECIES_SHROOMISH 285
#define SPECIES_BRELOOM 286
#define SPECIES_SLAKOTH 287
#define SPECIES_VIGOROTH 288
#define SPECIES_SLAKING 289
#define SPECIES_NINCADA 290
#define SPECIES_NINJASK 291
#define SPECIES_SHEDINJA 292
#define SPECIES_WHISMUR 293
#define SPECIES_LOUDRED 294
#define SPECIES_EXPLOUD 295
#define SPECIES_MAKUHITA 296
#define SPECIES_HARIYAMA 297
#define SPECIES_AZURILL 298
#define SPECIES_NOSEPASS 299
#define SPECIES_SKITTY 300
#define SPECIES_DELCATTY 301
#define SPECIES_SABLEYE 302
#define SPECIES_MAWILE 303
#define SPECIES_ARON 304
#define SPECIES_LAIRON 305
#define SPECIES_AGGRON 306
#define SPECIES_MEDITITE 307
#define SPECIES_MEDICHAM 308
#define SPECIES_ELECTRIKE 309
#define SPECIES_MANECTRIC 310
#define SPECIES_PLUSLE 311
#define SPECIES_MINUN 312
#define SPECIES_VOLBEAT 313
#define SPECIES_ILLUMISE 314
#define SPECIES_ROSELIA 315
#define SPECIES_GULPIN 316
#define SPECIES_SWALOT 317
#define SPECIES_CARVANHA 318
#define SPECIES_SHARPEDO 319
#define SPECIES_WAILMER 320
#define SPECIES_WAILORD 321
#define SPECIES_NUMEL 322
#define SPECIES_CAMERUPT 323
#define SPECIES_TORKOAL 324
#define SPECIES_SPOINK 325
#define SPECIES_GRUMPIG 326
#define SPECIES_SPINDA 327
#define SPECIES_TRAPINCH 328
#define SPECIES_VIBRAVA 329
#define SPECIES_FLYGON 330
#define SPECIES_CACNEA 331
#define SPECIES_CACTURNE 332
#define SPECIES_SWABLU 333
#define SPECIES_ALTARIA 334
#define SPECIES_ZANGOOSE 335
#define SPECIES_SEVIPER 336
#define SPECIES_LUNATONE 337
#define SPECIES_SOLROCK 338
#define SPECIES_BARBOACH 339
#define SPECIES_WHISCASH 340
#define SPECIES_CORPHISH 341
#define SPECIES_CRAWDAUNT 342
#define SPECIES_BALTOY 343
#define SPECIES_CLAYDOL 344
#define SPECIES_LILEEP 345
#define SPECIES_CRADILY 346
#define SPECIES_ANORITH 347
#define SPECIES_ARMALDO 348
#define SPECIES_FEEBAS 349
#define SPECIES_MILOTIC 350
#define SPECIES_CASTFORM 351
#define SPECIES_KECLEON 352
#define SPECIES_SHUPPET 353
#define SPECIES_BANETTE 354
#define SPECIES_DUSKULL 355
#define SPECIES_DUSCLOPS 356
#define SPECIES_TROPIUS 357
#define SPECIES_CHIMECHO 358
#define SPECIES_ABSOL 359
#define SPECIES_WYNAUT 360
#define SPECIES_SNORUNT 361
#define SPECIES_GLALIE 362
#define SPECIES_SPHEAL 363
#define SPECIES_SEALEO 364
#define SPECIES_WALREIN 365
#define SPECIES_CLAMPERL 366
#define SPECIES_HUNTAIL 367
#define SPECIES_GOREBYSS 368
#define SPECIES_RELICANTH 369
#define SPECIES_LUVDISC 370
#define SPECIES_BAGON 371
#define SPECIES_SHELGON 372
#define SPECIES_SALAMENCE 373
#define SPECIES_BELDUM 374
#define SPECIES_METANG 375
#define SPECIES_METAGROSS 376
#define SPECIES_REGIROCK 377
#define SPECIES_REGICE 378
#define SPECIES_REGISTEEL 379
#define SPECIES_LATIAS 380
#define SPECIES_LATIOS 381
#define SPECIES_KYOGRE 382
#define SPECIES_GROUDON 383
#define SPECIES_RAYQUAZA 384
#define SPECIES_JIRACHI 385
#define SPECIES_DEOXYS 386
#define SPECIES_TURTWIG 387
#define SPECIES_GROTLE 388
#define SPECIES_TORTERRA 389
#define SPECIES_CHIMCHAR 390
#define SPECIES_MONFERNO 391
#define SPECIES_INFERNAPE 392
#define SPECIES_PIPLUP 393
#define SPECIES_PRINPLUP 394
#define SPECIES_EMPOLEON 395
#define SPECIES_STARLY 396
#define SPECIES_STARAVIA 397
#define SPECIES_STARAPTOR 398
#define SPECIES_BIDOOF 399
#define SPECIES_BIBAREL 400
#define SPECIES_KRICKETOT 401
#define SPECIES_KRICKETUNE 402
#define SPECIES_SHINX 403
#define SPECIES_LUXIO 404
#define SPECIES_LUXRAY 405
#define SPECIES_BUDEW 406
#define SPECIES_ROSERADE 407
#define SPECIES_CRANIDOS 408
#define SPECIES_RAMPARDOS 409
#define SPECIES_SHIELDON 410
#define SPECIES_BASTIODON 411
#define SPECIES_BURMY 412
#define SPECIES_WORMADAM 413
#define SPECIES_MOTHIM 414
#define SPECIES_COMBEE 415
#define SPECIES_VESPIQUEN 416
#define SPECIES_PACHIRISU 417
#define SPECIES_BUIZEL 418
#define SPECIES_FLOATZEL 419
#define SPECIES_CHERUBI 420
#define SPECIES_CHERRIM 421
#define SPECIES_SHELLOS 422
#define SPECIES_GASTRODON 423
#define SPECIES_AMBIPOM 424
#define SPECIES_DRIFLOON 425
#define SPECIES_DRIFBLIM 426
#define SPECIES_BUNEARY 427
#define SPECIES_LOPUNNY 428
#define SPECIES_MISMAGIUS 429
#define SPECIES_HONCHKROW 430
#define SPECIES_GLAMEOW 431
#define SPECIES_PURUGLY 432
#define SPECIES_CHINGLING 433
#define SPECIES_STUNKY 434
#define SPECIES_SKUNTANK 435
#define SPECIES_BRONZOR 436
#define SPECIES_BRONZONG 437
#define SPECIES_BONSLY 438
#define SPECIES_MIME_JR 439
#define SPECIES_HAPPINY 440
#define SPECIES_CHATOT 441
#define SPECIES_SPIRITOMB 442
#define SPECIES_GIBLE 443
#define SPECIES_GABITE 444
#define SPECIES_GARCHOMP 445
#define SPECIES_MUNCHLAX 446
#define SPECIES_RIOLU 447
#define SPECIES_LUCARIO 448
#define SPECIES_HIPPOPOTAS 449
#define SPECIES_HIPPOWDON 450
#define SPECIES_SKORUPI 451
#define SPECIES_DRAPION 452
#define SPECIES_CROAGUNK 453
#define SPECIES_TOXICROAK 454
#define SPECIES_CARNIVINE 455
#define SPECIES_FINNEON 456
#define SPECIES_LUMINEON 457
#define SPECIES_MANTYKE 458
#define SPECIES_SNOVER 459
#define SPECIES_ABOMASNOW 460
#define SPECIES_WEAVILE 461
#define SPECIES_MAGNEZONE 462
#define SPECIES_LICKILICKY 463
#define SPECIES_RHYPERIOR 464
#define SPECIES_TANGROWTH 465
#define SPECIES_ELECTIVIRE 466
#define SPECIES_MAGMORTAR 467
#define SPECIES_TOGEKISS 468
#define SPECIES_YANMEGA 469
#define SPECIES_LEAFEON 470
#define SPECIES_GLACEON 471
#define SPECIES_GLISCOR 472
#define SPECIES_MAMOSWINE 473
#define SPECIES_PORYGON_Z 474
#define SPECIES_GALLADE 475
#define SPECIES_PROBOPASS 476
#define SPECIES_DUSKNOIR 477
#define SPECIES_FROSLASS 478
#define SPECIES_ROTOM 479
#define SPECIES_UXIE 480
#define SPECIES_MESPRIT 481
#define SPECIES_AZELF 482
#define SPECIES_DIALGA 483
#define SPECIES_PALKIA 484
#define SPECIES_HEATRAN 485
#define SPECIES_REGIGIGAS 486
#define SPECIES_GIRATINA 487
#define SPECIES_CRESSELIA 488
#define SPECIES_PHIONE 489
#define SPECIES_MANAPHY 490
#define SPECIES_DARKRAI 491
#define SPECIES_SHAYMIN 492
#define SPECIES_ARCEUS 493
#define SPECIES_VICTINI 494
#define SPECIES_SNIVY 495
#define SPECIES_SERVINE 496
#define SPECIES_SERPERIOR 497
#define SPECIES_TEPIG 498
#define SPECIES_PIGNITE 499
#define SPECIES_EMBOAR 500
#define SPECIES_OSHAWOTT 501
#define SPECIES_DEWOTT 502
#define SPECIES_SAMUROTT 503
#define SPECIES_PATRAT 504
#define SPECIES_WATCHOG 505
#define SPECIES_LILLIPUP 506
#define SPECIES_HERDIER 507
#define SPECIES_STOUTLAND 508
#define SPECIES_PURRLOIN 509
#define SPECIES_LIEPARD 510
#define SPECIES_PANSAGE 511
#define SPECIES_SIMISAGE 512
#define SPECIES_PANSEAR 513
#define SPECIES_SIMISEAR 514
#define SPECIES_PANPOUR 515
#define SPECIES_SIMIPOUR 516
#define SPECIES_MUNNA 517
#define SPECIES_MUSHARNA 518
#define SPECIES_PIDOVE 519
#define SPECIES_TRANQUILL 520
#define SPECIES_UNFEZANT 521
#define SPECIES_BLITZLE 522
#define SPECIES_ZEBSTRIKA 523
#define SPECIES_ROGGENROLA 524
#define SPECIES_BOLDORE 525
#define SPECIES_GIGALITH 526
#define SPECIES_WOOBAT 527
#define SPECIES_SWOOBAT 528
#define SPECIES_DRILBUR 529
#define SPECIES_EXCADRILL 530
#define SPECIES_AUDINO 531
#define SPECIES_TIMBURR 532
#define SPECIES_GURDURR 533
#define SPECIES_CONKELDURR 534
#define SPECIES_TYMPOLE 535
#define SPECIES_PALPITOAD 536
#define SPECIES_SEISMITOAD 537
#define SPECIES_THROH 538
#define SPECIES_SAWK 539
#define SPECIES_SEWADDLE 540
#define SPECIES_SWADLOON 541
#define SPECIES_LEAVANNY 542
#define SPECIES_VENIPEDE 543
#define SPECIES_WHIRLIPEDE 544
#define SPECIES_SCOLIPEDE 545
#define SPECIES_COTTONEE 546
#define SPECIES_WHIMSICOTT 547
#define SPECIES_PETILIL 548
#define SPECIES_LILLIGANT 549
#define SPECIES_BASCULIN 550
#define SPECIES_SANDILE 551
#define SPECIES_KROKOROK 552
#define SPECIES_KROOKODILE 553
#define SPECIES_DARUMAKA 554
#define SPECIES_DARMANITAN 555
#define SPECIES_MARACTUS 556
#define SPECIES_DWEBBLE 557
#define SPECIES_CRUSTLE 558
#define SPECIES_SCRAGGY 559
#define SPECIES_SCRAFTY 560
#define SPECIES_SIGILYPH 561
#define SPECIES_YAMASK 562
#define SPECIES_COFAGRIGUS 563
#define SPECIES_TIRTOUGA 564
#define SPECIES_CARRACOSTA 565
#define SPECIES_ARCHEN 566
#define SPECIES_ARCHEOPS 567
#define SPECIES_TRUBBISH 568
#define SPECIES_GARBODOR 569
#define SPECIES_ZORUA 570
#define SPECIES_ZOROARK 571
#define SPECIES_MINCCINO 572
#define SPECIES_CINCCINO 573
#define SPECIES_GOTHITA 574
#define SPECIES_GOTHORITA 575
#define SPECIES_GOTHITELLE 576
#define SPECIES_SOLOSIS 577
#define SPECIES_DUOSION 578
#define SPECIES_REUNICLUS 579
#define SPECIES_DUCKLETT 580
#define SPECIES_SWANNA 581
#define SPECIES_VANILLITE 582
#define SPECIES_VANILLISH 583
#define SPECIES_VANILLUXE 584
#define SPECIES_DEERLING 585
#define SPECIES_SAWSBUCK 586
#define SPECIES_EMOLGA 587
#define SPECIES_KARRABLAST 588
#define SPECIES_ESCAVALIER 589
#define SPECIES_FOONGUS 590
#define SPECIES_AMOONGUSS 591
#define SPECIES_FRILLISH 592
#define SPECIES_JELLICENT 593
#define SPECIES_ALOMOMOLA 594
#define SPECIES_JOLTIK 595
#define SPECIES_GALVANTULA 596
#define SPECIES_FERROSEED 597
#define SPECIES_FERROTHORN 598
#define SPECIES_KLINK 599
#define SPECIES_KLANG 600
#define SPECIES_KLINKLANG 601
#define SPECIES_TYNAMO 602
#define SPECIES_EELEKTRIK 603
#define SPECIES_EELEKTROSS 604
#define SPECIES_ELGYEM 605
#define SPECIES_BEHEEYEM 606
#define SPECIES_LITWICK 607
#define SPECIES_LAMPENT 608
#define SPECIES_CHANDELURE 609
#define SPECIES_AXEW 610
#define SPECIES_FRAXURE 611
#define SPECIES_HAXORUS 612
#define SPECIES_CUBCHOO 613
#define SPECIES_BEARTIC 614
#define SPECIES_CRYOGONAL 615
#define SPECIES_SHELMET 616
#define SPECIES_ACCELGOR 617
#define SPECIES_STUNFISK 618
#define SPECIES_MIENFOO 619
#define SPECIES_MIENSHAO 620
#define SPECIES_DRUDDIGON 621
#define SPECIES_GOLETT 622
#define SPECIES_GOLURK 623
#define SPECIES_PAWNIARD 624
#define SPECIES_BISHARP 625
#define SPECIES_BOUFFALANT 626
#define SPECIES_RUFFLET 627
#define SPECIES_BRAVIARY 628
#define SPECIES_VULLABY 629
#define SPECIES_MANDIBUZZ 630
#define SPECIES_HEATMOR 631
#define SPECIES_DURANT 632
#define SPECIES_DEINO 633
#define SPECIES_ZWEILOUS 634
#define SPECIES_HYDREIGON 635
#define SPECIES_LARVESTA 636
#define SPECIES_VOLCARONA 637
#define SPECIES_COBALION 638
#define SPECIES_TERRAKION 639
#define SPECIES_VIRIZION 640
#define SPECIES_TORNADUS 641
#define SPECIES_THUNDURUS 642
#define SPECIES_RESHIRAM 643
#define SPECIES_ZEKROM 644
#define SPECIES_LANDORUS 645
#define SPECIES_KYUREM 646
#define SPECIES_KELDEO 647
#define SPECIES_MELOETTA 648
#define SPECIES_GENESECT 649
#define SPECIES_CHESPIN 650
#define SPECIES_QUILLADIN 651
#define SPECIES_CHESNAUGHT 652
#define SPECIES_FENNEKIN 653
#define SPECIES_BRAIXEN 654
#define SPECIES_DELPHOX 655
#define SPECIES_FROAKIE 656
#define SPECIES_FROGADIER 657
#define SPECIES_GRENINJA 658
#define SPECIES_BUNNELBY 659
#define SPECIES_DIGGERSBY 660
#define SPECIES_FLETCHLING 661
#define SPECIES_FLETCHINDER 662
#define SPECIES_TALONFLAME 663
#define SPECIES_SCATTERBUG 664
#define SPECIES_SPEWPA 665
#define SPECIES_VIVILLON 666 // Icy Snow Pattern
#define SPECIES_LITLEO 667
#define SPECIES_PYROAR 668
#define SPECIES_FLABEBE 669 // Red Flower
#define SPECIES_FLOETTE 670
#define SPECIES_FLORGES 671
#define SPECIES_SKIDDO 672
#define SPECIES_GOGOAT 673
#define SPECIES_PANCHAM 674
#define SPECIES_PANGORO 675
#define SPECIES_FURFROU 676
#define SPECIES_ESPURR 677
#define SPECIES_MEOWSTIC 678
#define SPECIES_HONEDGE 679
#define SPECIES_DOUBLADE 680
#define SPECIES_AEGISLASH 681
#define SPECIES_SPRITZEE 682
#define SPECIES_AROMATISSE 683
#define SPECIES_SWIRLIX 684
#define SPECIES_SLURPUFF 685
#define SPECIES_INKAY 686
#define SPECIES_MALAMAR 687
#define SPECIES_BINACLE 688
#define SPECIES_BARBARACLE 689
#define SPECIES_SKRELP 690
#define SPECIES_DRAGALGE 691
#define SPECIES_CLAUNCHER 692
#define SPECIES_CLAWITZER 693
#define SPECIES_HELIOPTILE 694
#define SPECIES_HELIOLISK 695
#define SPECIES_TYRUNT 696
#define SPECIES_TYRANTRUM 697
#define SPECIES_AMAURA 698
#define SPECIES_AURORUS 699
#define SPECIES_SYLVEON 700
#define SPECIES_HAWLUCHA 701
#define SPECIES_DEDENNE 702
#define SPECIES_CARBINK 703
#define SPECIES_GOOMY 704
#define SPECIES_SLIGGOO 705
#define SPECIES_GOODRA 706
#define SPECIES_KLEFKI 707
#define SPECIES_PHANTUMP 708
#define SPECIES_TREVENANT 709
#define SPECIES_PUMPKABOO 710
#define SPECIES_GOURGEIST 711
#define SPECIES_BERGMITE 712
#define SPECIES_AVALUGG 713
#define SPECIES_NOIBAT 714
#define SPECIES_NOIVERN 715
#define SPECIES_XERNEAS 716
#define SPECIES_YVELTAL 717
#define SPECIES_ZYGARDE 718
#define SPECIES_DIANCIE 719
#define SPECIES_HOOPA 720
#define SPECIES_VOLCANION 721
#define SPECIES_ROWLET 722
#define SPECIES_DARTRIX 723
#define SPECIES_DECIDUEYE 724
#define SPECIES_LITTEN 725
#define SPECIES_TORRACAT 726
#define SPECIES_INCINEROAR 727
#define SPECIES_POPPLIO 728
#define SPECIES_BRIONNE 729
#define SPECIES_PRIMARINA 730
#define SPECIES_PIKIPEK 731
#define SPECIES_TRUMBEAK 732
#define SPECIES_TOUCANNON 733
#define SPECIES_YUNGOOS 734
#define SPECIES_GUMSHOOS 735
#define SPECIES_GRUBBIN 736
#define SPECIES_CHARJABUG 737
#define SPECIES_VIKAVOLT 738
#define SPECIES_CRABRAWLER 739
#define SPECIES_CRABOMINABLE 740
#define SPECIES_ORICORIO 741
#define SPECIES_CUTIEFLY 742
#define SPECIES_RIBOMBEE 743
#define SPECIES_ROCKRUFF 744
#define SPECIES_LYCANROC 745
#define SPECIES_WISHIWASHI 746
#define SPECIES_MAREANIE 747
#define SPECIES_TOXAPEX 748
#define SPECIES_MUDBRAY 749
#define SPECIES_MUDSDALE 750
#define SPECIES_DEWPIDER 751
#define SPECIES_ARAQUANID 752
#define SPECIES_FOMANTIS 753
#define SPECIES_LURANTIS 754
#define SPECIES_MORELULL 755
#define SPECIES_SHIINOTIC 756
#define SPECIES_SALANDIT 757
#define SPECIES_SALAZZLE 758
#define SPECIES_STUFFUL 759
#define SPECIES_BEWEAR 760
#define SPECIES_BOUNSWEET 761
#define SPECIES_STEENEE 762
#define SPECIES_TSAREENA 763
#define SPECIES_COMFEY 764
#define SPECIES_ORANGURU 765
#define SPECIES_PASSIMIAN 766
#define SPECIES_WIMPOD 767
#define SPECIES_GOLISOPOD 768
#define SPECIES_SANDYGAST 769
#define SPECIES_PALOSSAND 770
#define SPECIES_PYUKUMUKU 771
#define SPECIES_TYPE_NULL 772
#define SPECIES_SILVALLY 773
#define SPECIES_MINIOR 774
#define SPECIES_KOMALA 775
#define SPECIES_TURTONATOR 776
#define SPECIES_TOGEDEMARU 777
#define SPECIES_MIMIKYU 778
#define SPECIES_BRUXISH 779
#define SPECIES_DRAMPA 780
#define SPECIES_DHELMISE 781
#define SPECIES_JANGMO_O 782
#define SPECIES_HAKAMO_O 783
#define SPECIES_KOMMO_O 784
#define SPECIES_TAPU_KOKO 785
#define SPECIES_TAPU_LELE 786
#define SPECIES_TAPU_BULU 787
#define SPECIES_TAPU_FINI 788
#define SPECIES_COSMOG 789
#define SPECIES_COSMOEM 790
#define SPECIES_SOLGALEO 791
#define SPECIES_LUNALA 792
#define SPECIES_NIHILEGO 793
#define SPECIES_BUZZWOLE 794
#define SPECIES_PHEROMOSA 795
#define SPECIES_XURKITREE 796
#define SPECIES_CELESTEELA 797
#define SPECIES_KARTANA 798
#define SPECIES_GUZZLORD 799
#define SPECIES_NECROZMA 800
#define SPECIES_MAGEARNA 801
#define SPECIES_MARSHADOW 802
#define SPECIES_POIPOLE 803
#define SPECIES_NAGANADEL 804
#define SPECIES_STAKATAKA 805
#define SPECIES_BLACEPHALON 806
#define SPECIES_ZERAORA 807
#define SPECIES_MELTAN 808
#define SPECIES_MELMETAL 809
#define SPECIES_GROOKEY 810
#define SPECIES_THWACKEY 811
#define SPECIES_RILLABOOM 812
#define SPECIES_SCORBUNNY 813
#define SPECIES_RABOOT 814
#define SPECIES_CINDERACE 815
#define SPECIES_SOBBLE 816
#define SPECIES_DRIZZILE 817
#define SPECIES_INTELEON 818
#define SPECIES_SKWOVET 819
#define SPECIES_GREEDENT 820
#define SPECIES_ROOKIDEE 821
#define SPECIES_CORVISQUIRE 822
#define SPECIES_CORVIKNIGHT 823
#define SPECIES_BLIPBUG 824
#define SPECIES_DOTTLER 825
#define SPECIES_ORBEETLE 826
#define SPECIES_NICKIT 827
#define SPECIES_THIEVUL 828
#define SPECIES_GOSSIFLEUR 829
#define SPECIES_ELDEGOSS 830
#define SPECIES_WOOLOO 831
#define SPECIES_DUBWOOL 832
#define SPECIES_CHEWTLE 833
#define SPECIES_DREDNAW 834
#define SPECIES_YAMPER 835
#define SPECIES_BOLTUND 836
#define SPECIES_ROLYCOLY 837
#define SPECIES_CARKOL 838
#define SPECIES_COALOSSAL 839
#define SPECIES_APPLIN 840
#define SPECIES_FLAPPLE 841
#define SPECIES_APPLETUN 842
#define SPECIES_SILICOBRA 843
#define SPECIES_SANDACONDA 844
#define SPECIES_CRAMORANT 845
#define SPECIES_ARROKUDA 846
#define SPECIES_BARRASKEWDA 847
#define SPECIES_TOXEL 848
#define SPECIES_TOXTRICITY 849
#define SPECIES_SIZZLIPEDE 850
#define SPECIES_CENTISKORCH 851
#define SPECIES_CLOBBOPUS 852
#define SPECIES_GRAPPLOCT 853
#define SPECIES_SINISTEA 854
#define SPECIES_POLTEAGEIST 855
#define SPECIES_HATENNA 856
#define SPECIES_HATTREM 857
#define SPECIES_HATTERENE 858
#define SPECIES_IMPIDIMP 859
#define SPECIES_MORGREM 860
#define SPECIES_GRIMMSNARL 861
#define SPECIES_OBSTAGOON 862
#define SPECIES_PERRSERKER 863
#define SPECIES_CURSOLA 864
#define SPECIES_SIRFETCHD 865
#define SPECIES_MR_RIME 866
#define SPECIES_RUNERIGUS 867
#define SPECIES_MILCERY 868
#define SPECIES_ALCREMIE 869
#define SPECIES_FALINKS 870
#define SPECIES_PINCURCHIN 871
#define SPECIES_SNOM 872
#define SPECIES_FROSMOTH 873
#define SPECIES_STONJOURNER 874
#define SPECIES_EISCUE 875
#define SPECIES_INDEEDEE 876
#define SPECIES_MORPEKO 877
#define SPECIES_CUFANT 878
#define SPECIES_COPPERAJAH 879
#define SPECIES_DRACOZOLT 880
#define SPECIES_ARCTOZOLT 881
#define SPECIES_DRACOVISH 882
#define SPECIES_ARCTOVISH 883
#define SPECIES_DURALUDON 884
#define SPECIES_DREEPY 885
#define SPECIES_DRAKLOAK 886
#define SPECIES_DRAGAPULT 887
#define SPECIES_ZACIAN 888
#define SPECIES_ZAMAZENTA 889
#define SPECIES_ETERNATUS 890
#define SPECIES_KUBFU 891
#define SPECIES_URSHIFU 892
#define SPECIES_ZARUDE 893
#define SPECIES_REGIELEKI 894
#define SPECIES_REGIDRAGO 895
#define SPECIES_GLASTRIER 896
#define SPECIES_SPECTRIER 897
#define SPECIES_CALYREX 898
#define SPECIES_WYRDEER 899
#define SPECIES_KLEAVOR 900
#define SPECIES_URSALUNA 901
#define SPECIES_BASCULEGION 902
#define SPECIES_SNEASLER 903
#define SPECIES_OVERQWIL 904
#define SPECIES_ENAMORUS 905

#define FORMS_START SPECIES_ENAMORUS

// Megas
#define SPECIES_VENUSAUR_MEGA                FORMS_START + 1
#define SPECIES_CHARIZARD_MEGA_X             FORMS_START + 2
#define SPECIES_CHARIZARD_MEGA_Y             FORMS_START + 3
#define SPECIES_BLASTOISE_MEGA               FORMS_START + 4
#define SPECIES_BEEDRILL_MEGA                FORMS_START + 5
#define SPECIES_PIDGEOT_MEGA                 FORMS_START + 6
#define SPECIES_ALAKAZAM_MEGA                FORMS_START + 7
#define SPECIES_SLOWBRO_MEGA                 FORMS_START + 8
#define SPECIES_GENGAR_MEGA                  FORMS_START + 9
#define SPECIES_KANGASKHAN_MEGA              FORMS_START + 10
#define SPECIES_PINSIR_MEGA                  FORMS_START + 11
#define SPECIES_GYARADOS_MEGA                FORMS_START + 12
#define SPECIES_AERODACTYL_MEGA              FORMS_START + 13
#define SPECIES_MEWTWO_MEGA_X                FORMS_START + 14
#define SPECIES_MEWTWO_MEGA_Y                FORMS_START + 15
#define SPECIES_AMPHAROS_MEGA                FORMS_START + 16
#define SPECIES_STEELIX_MEGA                 FORMS_START + 17
#define SPECIES_SCIZOR_MEGA                  FORMS_START + 18
#define SPECIES_HERACROSS_MEGA               FORMS_START + 19
#define SPECIES_HOUNDOOM_MEGA                FORMS_START + 20
#define SPECIES_TYRANITAR_MEGA               FORMS_START + 21
#define SPECIES_SCEPTILE_MEGA                FORMS_START + 22
#define SPECIES_BLAZIKEN_MEGA                FORMS_START + 23
#define SPECIES_SWAMPERT_MEGA                FORMS_START + 24
#define SPECIES_GARDEVOIR_MEGA               FORMS_START + 25
#define SPECIES_SABLEYE_MEGA                 FORMS_START + 26
#define SPECIES_MAWILE_MEGA                  FORMS_START + 27
#define SPECIES_AGGRON_MEGA                  FORMS_START + 28
#define SPECIES_MEDICHAM_MEGA                FORMS_START + 29
#define SPECIES_MANECTRIC_MEGA               FORMS_START + 30
#define SPECIES_SHARPEDO_MEGA                FORMS_START + 31
#define SPECIES_CAMERUPT_MEGA                FORMS_START + 32
#define SPECIES_ALTARIA_MEGA                 FORMS_START + 33
#define SPECIES_BANETTE_MEGA                 FORMS_START + 34
#define SPECIES_ABSOL_MEGA                   FORMS_START + 35
#define SPECIES_GLALIE_MEGA                  FORMS_START + 36
#define SPECIES_SALAMENCE_MEGA               FORMS_START + 37
#define SPECIES_METAGROSS_MEGA               FORMS_START + 38
#define SPECIES_LATIAS_MEGA                  FORMS_START + 39
#define SPECIES_LATIOS_MEGA                  FORMS_START + 40
#define SPECIES_LOPUNNY_MEGA                 FORMS_START + 41
#define SPECIES_GARCHOMP_MEGA                FORMS_START + 42
#define SPECIES_LUCARIO_MEGA                 FORMS_START + 43
#define SPECIES_ABOMASNOW_MEGA               FORMS_START + 44
#define SPECIES_GALLADE_MEGA                 FORMS_START + 45
#define SPECIES_AUDINO_MEGA                  FORMS_START + 46
#define SPECIES_DIANCIE_MEGA                 FORMS_START + 47

// Special Mega + Primals
#define SPECIES_RAYQUAZA_MEGA                FORMS_START + 48
#define SPECIES_KYOGRE_PRIMAL                FORMS_START + 49
#define SPECIES_GROUDON_PRIMAL               FORMS_START + 50

// Alolan Forms
#define SPECIES_RATTATA_ALOLAN               FORMS_START + 51
#define SPECIES_RATICATE_ALOLAN              FORMS_START + 52
#define SPECIES_RAICHU_ALOLAN                FORMS_START + 53
#define SPECIES_SANDSHREW_ALOLAN             FORMS_START + 54
#define SPECIES_SANDSLASH_ALOLAN             FORMS_START + 55
#define SPECIES_VULPIX_ALOLAN                FORMS_START + 56
#define SPECIES_NINETALES_ALOLAN             FORMS_START + 57
#define SPECIES_DIGLETT_ALOLAN               FORMS_START + 58
#define SPECIES_DUGTRIO_ALOLAN               FORMS_START + 59
#define SPECIES_MEOWTH_ALOLAN                FORMS_START + 60
#define SPECIES_PERSIAN_ALOLAN               FORMS_START + 61
#define SPECIES_GEODUDE_ALOLAN               FORMS_START + 62
#define SPECIES_GRAVELER_ALOLAN              FORMS_START + 63
#define SPECIES_GOLEM_ALOLAN                 FORMS_START + 64
#define SPECIES_GRIMER_ALOLAN                FORMS_START + 65
#define SPECIES_MUK_ALOLAN                   FORMS_START + 66
#define SPECIES_EXEGGUTOR_ALOLAN             FORMS_START + 67
#define SPECIES_MAROWAK_ALOLAN               FORMS_START + 68

// Galarian Forms
#define SPECIES_MEOWTH_GALARIAN              FORMS_START + 69
#define SPECIES_PONYTA_GALARIAN              FORMS_START + 70
#define SPECIES_RAPIDASH_GALARIAN            FORMS_START + 71
#define SPECIES_SLOWPOKE_GALARIAN            FORMS_START + 72
#define SPECIES_SLOWBRO_GALARIAN             FORMS_START + 73
#define SPECIES_FARFETCHD_GALARIAN           FORMS_START + 74
#define SPECIES_WEEZING_GALARIAN             FORMS_START + 75
#define SPECIES_MR_MIME_GALARIAN             FORMS_START + 76
#define SPECIES_ARTICUNO_GALARIAN            FORMS_START + 77
#define SPECIES_ZAPDOS_GALARIAN              FORMS_START + 78
#define SPECIES_MOLTRES_GALARIAN             FORMS_START + 79
#define SPECIES_SLOWKING_GALARIAN            FORMS_START + 80
#define SPECIES_CORSOLA_GALARIAN             FORMS_START + 81
#define SPECIES_ZIGZAGOON_GALARIAN           FORMS_START + 82
#define SPECIES_LINOONE_GALARIAN             FORMS_START + 83
#define SPECIES_DARUMAKA_GALARIAN            FORMS_START + 84
#define SPECIES_DARMANITAN_GALARIAN          FORMS_START + 85
#define SPECIES_YAMASK_GALARIAN              FORMS_START + 86
#define SPECIES_STUNFISK_GALARIAN            FORMS_START + 87

//Hisuian Forms
#define SPECIES_GROWLITHE_HISUIAN            FORMS_START + 88
#define SPECIES_ARCANINE_HISUIAN             FORMS_START + 89
#define SPECIES_VOLTORB_HISUIAN              FORMS_START + 90
#define SPECIES_ELECTRODE_HISUIAN            FORMS_START + 91
#define SPECIES_TYPHLOSION_HISUIAN           FORMS_START + 92
#define SPECIES_QWILFISH_HISUIAN             FORMS_START + 93
#define SPECIES_SNEASEL_HISUIAN              FORMS_START + 94
#define SPECIES_SAMUROTT_HISUIAN             FORMS_START + 95
#define SPECIES_LILLIGANT_HISUIAN            FORMS_START + 96
#define SPECIES_ZORUA_HISUIAN                FORMS_START + 97
#define SPECIES_ZOROARK_HISUIAN              FORMS_START + 98
#define SPECIES_BRAVIARY_HISUIAN             FORMS_START + 99
#define SPECIES_SLIGGOO_HISUIAN              FORMS_START + 100
#define SPECIES_GOODRA_HISUIAN               FORMS_START + 101
#define SPECIES_AVALUGG_HISUIAN              FORMS_START + 102
#define SPECIES_DECIDUEYE_HISUIAN            FORMS_START + 103

// Misc Forms

// Cosplay Pikachu
#define SPECIES_PIKACHU_COSPLAY              FORMS_START + 104
#define SPECIES_PIKACHU_ROCK_STAR            FORMS_START + 105
#define SPECIES_PIKACHU_BELLE                FORMS_START + 106
#define SPECIES_PIKACHU_POP_STAR             FORMS_START + 107
#define SPECIES_PIKACHU_PH_D                 FORMS_START + 108
#define SPECIES_PIKACHU_LIBRE                FORMS_START + 109

// Cap Pikachu
#define SPECIES_PIKACHU_ORIGINAL_CAP         FORMS_START + 110
#define SPECIES_PIKACHU_HOENN_CAP            FORMS_START + 111
#define SPECIES_PIKACHU_SINNOH_CAP           FORMS_START + 112
#define SPECIES_PIKACHU_UNOVA_CAP            FORMS_START + 113
#define SPECIES_PIKACHU_KALOS_CAP            FORMS_START + 114
#define SPECIES_PIKACHU_ALOLA_CAP            FORMS_START + 115
#define SPECIES_PIKACHU_PARTNER_CAP          FORMS_START + 116
#define SPECIES_PIKACHU_WORLD_CAP            FORMS_START + 117

// Pichu
#define SPECIES_PICHU_SPIKY_EARED            FORMS_START + 118

// Unown
#define SPECIES_UNOWN_B                      FORMS_START + 119
#define SPECIES_UNOWN_C                      FORMS_START + 120
#define SPECIES_UNOWN_D                      FORMS_START + 121
#define SPECIES_UNOWN_E                      FORMS_START + 122
#define SPECIES_UNOWN_F                      FORMS_START + 123
#define SPECIES_UNOWN_G                      FORMS_START + 124
#define SPECIES_UNOWN_H                      FORMS_START + 125
#define SPECIES_UNOWN_I                      FORMS_START + 126
#define SPECIES_UNOWN_J                      FORMS_START + 127
#define SPECIES_UNOWN_K                      FORMS_START + 128
#define SPECIES_UNOWN_L                      FORMS_START + 129
#define SPECIES_UNOWN_M                      FORMS_START + 130
#define SPECIES_UNOWN_N                      FORMS_START + 131
#define SPECIES_UNOWN_O                      FORMS_START + 132
#define SPECIES_UNOWN_P                      FORMS_START + 133
#define SPECIES_UNOWN_Q                      FORMS_START + 134
#define SPECIES_UNOWN_R                      FORMS_START + 135
#define SPECIES_UNOWN_S                      FORMS_START + 136
#define SPECIES_UNOWN_T                      FORMS_START + 137
#define SPECIES_UNOWN_U                      FORMS_START + 138
#define SPECIES_UNOWN_V                      FORMS_START + 139
#define SPECIES_UNOWN_W                      FORMS_START + 140
#define SPECIES_UNOWN_X                      FORMS_START + 141
#define SPECIES_UNOWN_Y                      FORMS_START + 142
#define SPECIES_UNOWN_Z                      FORMS_START + 143
#define SPECIES_UNOWN_EMARK                  FORMS_START + 144
#define SPECIES_UNOWN_QMARK                  FORMS_START + 145

// Castform
#define SPECIES_CASTFORM_SUNNY               FORMS_START + 146
#define SPECIES_CASTFORM_RAINY               FORMS_START + 147
#define SPECIES_CASTFORM_SNOWY               FORMS_START + 148

// Deoxys
#define SPECIES_DEOXYS_ATTACK                FORMS_START + 149
#define SPECIES_DEOXYS_DEFENSE               FORMS_START + 150
#define SPECIES_DEOXYS_SPEED                 FORMS_START + 151

// Burmy
#define SPECIES_BURMY_SANDY_CLOAK            FORMS_START + 152
#define SPECIES_BURMY_TRASH_CLOAK            FORMS_START + 153

// Wormadam
#define SPECIES_WORMADAM_SANDY_CLOAK         FORMS_START + 154
#define SPECIES_WORMADAM_TRASH_CLOAK         FORMS_START + 155

// Cherrim
#define SPECIES_CHERRIM_SUNSHINE             FORMS_START + 156

// Shellos
#define SPECIES_SHELLOS_EAST_SEA             FORMS_START + 157

// Gastrodon
#define SPECIES_GASTRODON_EAST_SEA           FORMS_START + 158

// Rotom
#define SPECIES_ROTOM_HEAT                   FORMS_START + 159
#define SPECIES_ROTOM_WASH                   FORMS_START + 160
#define SPECIES_ROTOM_FROST                  FORMS_START + 161
#define SPECIES_ROTOM_FAN                    FORMS_START + 162
#define SPECIES_ROTOM_MOW                    FORMS_START + 163

// Origin Forme
#define SPECIES_DIALGA_ORIGIN                FORMS_START + 164
#define SPECIES_PALKIA_ORIGIN                FORMS_START + 165
#define SPECIES_GIRATINA_ORIGIN              FORMS_START + 166

// Shaymin
#define SPECIES_SHAYMIN_SKY                  FORMS_START + 167

// Arceus
#define SPECIES_ARCEUS_FIGHTING              FORMS_START + 168
#define SPECIES_ARCEUS_FLYING                FORMS_START + 169
#define SPECIES_ARCEUS_POISON                FORMS_START + 170
#define SPECIES_ARCEUS_GROUND                FORMS_START + 171
#define SPECIES_ARCEUS_ROCK                  FORMS_START + 172
#define SPECIES_ARCEUS_BUG                   FORMS_START + 173
#define SPECIES_ARCEUS_GHOST                 FORMS_START + 174
#define SPECIES_ARCEUS_STEEL                 FORMS_START + 175
#define SPECIES_ARCEUS_FIRE                  FORMS_START + 176
#define SPECIES_ARCEUS_WATER                 FORMS_START + 177
#define SPECIES_ARCEUS_GRASS                 FORMS_START + 178
#define SPECIES_ARCEUS_ELECTRIC              FORMS_START + 179
#define SPECIES_ARCEUS_PSYCHIC               FORMS_START + 180
#define SPECIES_ARCEUS_ICE                   FORMS_START + 181
#define SPECIES_ARCEUS_DRAGON                FORMS_START + 182
#define SPECIES_ARCEUS_DARK                  FORMS_START + 183
#define SPECIES_ARCEUS_FAIRY                 FORMS_START + 184

// Basculin
#define SPECIES_BASCULIN_BLUE_STRIPED        FORMS_START + 185
#define SPECIES_BASCULIN_WHITE_STRIPED       FORMS_START + 186

// Darmanitan
#define SPECIES_DARMANITAN_ZEN_MODE          FORMS_START + 187
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN FORMS_START + 188

// Deerling
#define SPECIES_DEERLING_SUMMER              FORMS_START + 189
#define SPECIES_DEERLING_AUTUMN              FORMS_START + 190
#define SPECIES_DEERLING_WINTER              FORMS_START + 191

// Sawsbuck
#define SPECIES_SAWSBUCK_SUMMER              FORMS_START + 192
#define SPECIES_SAWSBUCK_AUTUMN              FORMS_START + 193
#define SPECIES_SAWSBUCK_WINTER              FORMS_START + 194

// Therian Forms
#define SPECIES_TORNADUS_THERIAN             FORMS_START + 195
#define SPECIES_THUNDURUS_THERIAN            FORMS_START + 196
#define SPECIES_LANDORUS_THERIAN             FORMS_START + 197
#define SPECIES_ENAMORUS_THERIAN             FORMS_START + 198

// Kyurem
#define SPECIES_KYUREM_WHITE                 FORMS_START + 199
#define SPECIES_KYUREM_BLACK                 FORMS_START + 200

// Keldeo
#define SPECIES_KELDEO_RESOLUTE              FORMS_START + 201

// Meloetta
#define SPECIES_MELOETTA_PIROUETTE           FORMS_START + 202

// Genesect
#define SPECIES_GENESECT_DOUSE_DRIVE         FORMS_START + 203
#define SPECIES_GENESECT_SHOCK_DRIVE         FORMS_START + 204
#define SPECIES_GENESECT_BURN_DRIVE          FORMS_START + 205
#define SPECIES_GENESECT_CHILL_DRIVE         FORMS_START + 206

// Greninja
#define SPECIES_GRENINJA_BATTLE_BOND         FORMS_START + 207
#define SPECIES_GRENINJA_ASH                 FORMS_START + 208

// Vivillon
#define SPECIES_VIVILLON_POLAR               FORMS_START + 209
#define SPECIES_VIVILLON_TUNDRA              FORMS_START + 210
#define SPECIES_VIVILLON_CONTINENTAL         FORMS_START + 211
#define SPECIES_VIVILLON_GARDEN              FORMS_START + 212
#define SPECIES_VIVILLON_ELEGANT             FORMS_START + 213
#define SPECIES_VIVILLON_MEADOW              FORMS_START + 214
#define SPECIES_VIVILLON_MODERN              FORMS_START + 215
#define SPECIES_VIVILLON_MARINE              FORMS_START + 216
#define SPECIES_VIVILLON_ARCHIPELAGO         FORMS_START + 217
#define SPECIES_VIVILLON_HIGH_PLAINS         FORMS_START + 218
#define SPECIES_VIVILLON_SANDSTORM           FORMS_START + 219
#define SPECIES_VIVILLON_RIVER               FORMS_START + 220
#define SPECIES_VIVILLON_MONSOON             FORMS_START + 221
#define SPECIES_VIVILLON_SAVANNA             FORMS_START + 222
#define SPECIES_VIVILLON_SUN                 FORMS_START + 223
#define SPECIES_VIVILLON_OCEAN               FORMS_START + 224
#define SPECIES_VIVILLON_JUNGLE              FORMS_START + 225
#define SPECIES_VIVILLON_FANCY               FORMS_START + 226
#define SPECIES_VIVILLON_POKE_BALL           FORMS_START + 227

// Flabébé
#define SPECIES_FLABEBE_YELLOW_FLOWER        FORMS_START + 228
#define SPECIES_FLABEBE_ORANGE_FLOWER        FORMS_START + 229
#define SPECIES_FLABEBE_BLUE_FLOWER          FORMS_START + 230
#define SPECIES_FLABEBE_WHITE_FLOWER         FORMS_START + 231

// Floette
#define SPECIES_FLOETTE_YELLOW_FLOWER        FORMS_START + 232
#define SPECIES_FLOETTE_ORANGE_FLOWER        FORMS_START + 233
#define SPECIES_FLOETTE_BLUE_FLOWER          FORMS_START + 234
#define SPECIES_FLOETTE_WHITE_FLOWER         FORMS_START + 235
#define SPECIES_FLOETTE_ETERNAL_FLOWER       FORMS_START + 236

// Florges
#define SPECIES_FLORGES_YELLOW_FLOWER        FORMS_START + 237
#define SPECIES_FLORGES_ORANGE_FLOWER        FORMS_START + 238
#define SPECIES_FLORGES_BLUE_FLOWER          FORMS_START + 239
#define SPECIES_FLORGES_WHITE_FLOWER         FORMS_START + 240

// Furfrou
#define SPECIES_FURFROU_HEART_TRIM           FORMS_START + 241
#define SPECIES_FURFROU_STAR_TRIM            FORMS_START + 242
#define SPECIES_FURFROU_DIAMOND_TRIM         FORMS_START + 243
#define SPECIES_FURFROU_DEBUTANTE_TRIM       FORMS_START + 244
#define SPECIES_FURFROU_MATRON_TRIM          FORMS_START + 245
#define SPECIES_FURFROU_DANDY_TRIM           FORMS_START + 246
#define SPECIES_FURFROU_LA_REINE_TRIM        FORMS_START + 247
#define SPECIES_FURFROU_KABUKI_TRIM          FORMS_START + 248
#define SPECIES_FURFROU_PHARAOH_TRIM         FORMS_START + 249

// Meowstic
#define SPECIES_MEOWSTIC_FEMALE              FORMS_START + 250

// Aegislash
#define SPECIES_AEGISLASH_BLADE              FORMS_START + 251

// Pumpkaboo
#define SPECIES_PUMPKABOO_SMALL              FORMS_START + 252
#define SPECIES_PUMPKABOO_LARGE              FORMS_START + 253
#define SPECIES_PUMPKABOO_SUPER              FORMS_START + 254

// Gourgeist
#define SPECIES_GOURGEIST_SMALL              FORMS_START + 255
#define SPECIES_GOURGEIST_LARGE              FORMS_START + 256
#define SPECIES_GOURGEIST_SUPER              FORMS_START + 257

// Xerneas
#define SPECIES_XERNEAS_ACTIVE               FORMS_START + 258

// Zygarde
#define SPECIES_ZYGARDE_10                   FORMS_START + 259
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT   FORMS_START + 260
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT   FORMS_START + 261
#define SPECIES_ZYGARDE_COMPLETE             FORMS_START + 262

// Hoopa
#define SPECIES_HOOPA_UNBOUND                FORMS_START + 263

// Oricorio
#define SPECIES_ORICORIO_POM_POM             FORMS_START + 264
#define SPECIES_ORICORIO_PAU                 FORMS_START + 265
#define SPECIES_ORICORIO_SENSU               FORMS_START + 266

// Rockruff
#define SPECIES_ROCKRUFF_OWN_TEMPO           FORMS_START + 267

// Lycanroc
#define SPECIES_LYCANROC_MIDNIGHT            FORMS_START + 268
#define SPECIES_LYCANROC_DUSK                FORMS_START + 269

// Wishiwashi
#define SPECIES_WISHIWASHI_SCHOOL            FORMS_START + 270

// Silvally
#define SPECIES_SILVALLY_FIGHTING            FORMS_START + 271
#define SPECIES_SILVALLY_FLYING              FORMS_START + 272
#define SPECIES_SILVALLY_POISON              FORMS_START + 273
#define SPECIES_SILVALLY_GROUND              FORMS_START + 274
#define SPECIES_SILVALLY_ROCK                FORMS_START + 275
#define SPECIES_SILVALLY_BUG                 FORMS_START + 276
#define SPECIES_SILVALLY_GHOST               FORMS_START + 277
#define SPECIES_SILVALLY_STEEL               FORMS_START + 278
#define SPECIES_SILVALLY_FIRE                FORMS_START + 279
#define SPECIES_SILVALLY_WATER               FORMS_START + 280
#define SPECIES_SILVALLY_GRASS               FORMS_START + 281
#define SPECIES_SILVALLY_ELECTRIC            FORMS_START + 282
#define SPECIES_SILVALLY_PSYCHIC             FORMS_START + 283
#define SPECIES_SILVALLY_ICE                 FORMS_START + 284
#define SPECIES_SILVALLY_DRAGON              FORMS_START + 285
#define SPECIES_SILVALLY_DARK                FORMS_START + 286
#define SPECIES_SILVALLY_FAIRY               FORMS_START + 287

// Minior
#define SPECIES_MINIOR_METEOR_ORANGE         FORMS_START + 288
#define SPECIES_MINIOR_METEOR_YELLOW         FORMS_START + 289
#define SPECIES_MINIOR_METEOR_GREEN          FORMS_START + 290
#define SPECIES_MINIOR_METEOR_BLUE           FORMS_START + 291
#define SPECIES_MINIOR_METEOR_INDIGO         FORMS_START + 292
#define SPECIES_MINIOR_METEOR_VIOLET         FORMS_START + 293
#define SPECIES_MINIOR_CORE_RED              FORMS_START + 294
#define SPECIES_MINIOR_CORE_ORANGE           FORMS_START + 295
#define SPECIES_MINIOR_CORE_YELLOW           FORMS_START + 296
#define SPECIES_MINIOR_CORE_GREEN            FORMS_START + 297
#define SPECIES_MINIOR_CORE_BLUE             FORMS_START + 298
#define SPECIES_MINIOR_CORE_INDIGO           FORMS_START + 299
#define SPECIES_MINIOR_CORE_VIOLET           FORMS_START + 300

// Mimikyu
#define SPECIES_MIMIKYU_BUSTED               FORMS_START + 301

// Necrozma
#define SPECIES_NECROZMA_DUSK_MANE           FORMS_START + 302
#define SPECIES_NECROZMA_DAWN_WINGS          FORMS_START + 303
#define SPECIES_NECROZMA_ULTRA               FORMS_START + 304

// Magearna
#define SPECIES_MAGEARNA_ORIGINAL_COLOR      FORMS_START + 305

// Cramorant
#define SPECIES_CRAMORANT_GULPING            FORMS_START + 306
#define SPECIES_CRAMORANT_GORGING            FORMS_START + 307

// Toxtricity
#define SPECIES_TOXTRICITY_LOW_KEY           FORMS_START + 308

// Sinistea
#define SPECIES_SINISTEA_ANTIQUE             FORMS_START + 309

// Polteageist
#define SPECIES_POLTEAGEIST_ANTIQUE          FORMS_START + 310

// Alcremie
#define SPECIES_ALCREMIE_RUBY_CREAM          FORMS_START + 311
#define SPECIES_ALCREMIE_MATCHA_CREAM        FORMS_START + 312
#define SPECIES_ALCREMIE_MINT_CREAM          FORMS_START + 313
#define SPECIES_ALCREMIE_LEMON_CREAM         FORMS_START + 314
#define SPECIES_ALCREMIE_SALTED_CREAM        FORMS_START + 315
#define SPECIES_ALCREMIE_RUBY_SWIRL          FORMS_START + 316
#define SPECIES_ALCREMIE_CARAMEL_SWIRL       FORMS_START + 317
#define SPECIES_ALCREMIE_RAINBOW_SWIRL       FORMS_START + 318

// Eiscue
#define SPECIES_EISCUE_NOICE_FACE            FORMS_START + 319

// Indeedee
#define SPECIES_INDEEDEE_FEMALE              FORMS_START + 320

// Morpeko
#define SPECIES_MORPEKO_HANGRY               FORMS_START + 321

// Zacian
#define SPECIES_ZACIAN_CROWNED_SWORD         FORMS_START + 322

// Zamazenta
#define SPECIES_ZAMAZENTA_CROWNED_SHIELD     FORMS_START + 323

// Eternatus
#define SPECIES_ETERNATUS_ETERNAMAX          FORMS_START + 324

// Urshifu
#define SPECIES_URSHIFU_RAPID_STRIKE_STYLE   FORMS_START + 325

// Zarude
#define SPECIES_ZARUDE_DADA                  FORMS_START + 326

// Calyrex
#define SPECIES_CALYREX_ICE_RIDER            FORMS_START + 327
#define SPECIES_CALYREX_SHADOW_RIDER         FORMS_START + 328

#define SPECIAL_TRAIT_START SPECIES_CALYREX_SHADOW_RIDER

#define SPECIES_BULBASAUR_SPECIAL_TRAIT +1
#define SPECIES_IVYSAUR_SPECIAL_TRAIT +2
#define SPECIES_VENUSAUR_SPECIAL_TRAIT +3
#define SPECIES_CHARMANDER_SPECIAL_TRAIT +4
#define SPECIES_CHARMELEON_SPECIAL_TRAIT +5
#define SPECIES_CHARIZARD_SPECIAL_TRAIT +6
#define SPECIES_SQUIRTLE_SPECIAL_TRAIT +7
#define SPECIES_WARTORTLE_SPECIAL_TRAIT +8
#define SPECIES_BLASTOISE_SPECIAL_TRAIT +9
#define SPECIES_CATERPIE_SPECIAL_TRAIT +10
#define SPECIES_METAPOD_SPECIAL_TRAIT +11
#define SPECIES_BUTTERFREE_SPECIAL_TRAIT +12
#define SPECIES_WEEDLE_SPECIAL_TRAIT +13
#define SPECIES_KAKUNA_SPECIAL_TRAIT +14
#define SPECIES_BEEDRILL_SPECIAL_TRAIT +15
#define SPECIES_PIDGEY_SPECIAL_TRAIT +16
#define SPECIES_PIDGEOTTO_SPECIAL_TRAIT +17
#define SPECIES_PIDGEOT_SPECIAL_TRAIT +18
#define SPECIES_RATTATA_SPECIAL_TRAIT +19
#define SPECIES_RATICATE_SPECIAL_TRAIT +20
#define SPECIES_SPEAROW_SPECIAL_TRAIT +21
#define SPECIES_FEAROW_SPECIAL_TRAIT +22
#define SPECIES_EKANS_SPECIAL_TRAIT +23
#define SPECIES_ARBOK_SPECIAL_TRAIT +24
#define SPECIES_PIKACHU_SPECIAL_TRAIT +25
#define SPECIES_RAICHU_SPECIAL_TRAIT +26
#define SPECIES_SANDSHREW_SPECIAL_TRAIT +27
#define SPECIES_SANDSLASH_SPECIAL_TRAIT +28
#define SPECIES_NIDORAN_F_SPECIAL_TRAIT +29
#define SPECIES_NIDORINA_SPECIAL_TRAIT +30
#define SPECIES_NIDOQUEEN_SPECIAL_TRAIT +31
#define SPECIES_NIDORAN_M_SPECIAL_TRAIT +32
#define SPECIES_NIDORINO_SPECIAL_TRAIT +33
#define SPECIES_NIDOKING_SPECIAL_TRAIT +34
#define SPECIES_CLEFAIRY_SPECIAL_TRAIT +35
#define SPECIES_CLEFABLE_SPECIAL_TRAIT +36
#define SPECIES_VULPIX_SPECIAL_TRAIT +37
#define SPECIES_NINETALES_SPECIAL_TRAIT +38
#define SPECIES_JIGGLYPUFF_SPECIAL_TRAIT +39
#define SPECIES_WIGGLYTUFF_SPECIAL_TRAIT +40
#define SPECIES_ZUBAT_SPECIAL_TRAIT +41
#define SPECIES_GOLBAT_SPECIAL_TRAIT +42
#define SPECIES_ODDISH_SPECIAL_TRAIT +43
#define SPECIES_GLOOM_SPECIAL_TRAIT +44
#define SPECIES_VILEPLUME_SPECIAL_TRAIT +45
#define SPECIES_PARAS_SPECIAL_TRAIT +46
#define SPECIES_PARASECT_SPECIAL_TRAIT +47
#define SPECIES_VENONAT_SPECIAL_TRAIT +48
#define SPECIES_VENOMOTH_SPECIAL_TRAIT +49
#define SPECIES_DIGLETT_SPECIAL_TRAIT +50
#define SPECIES_DUGTRIO_SPECIAL_TRAIT +51
#define SPECIES_MEOWTH_SPECIAL_TRAIT +52
#define SPECIES_PERSIAN_SPECIAL_TRAIT +53
#define SPECIES_PSYDUCK_SPECIAL_TRAIT +54
#define SPECIES_GOLDUCK_SPECIAL_TRAIT +55
#define SPECIES_MANKEY_SPECIAL_TRAIT +56
#define SPECIES_PRIMEAPE_SPECIAL_TRAIT +57
#define SPECIES_GROWLITHE_SPECIAL_TRAIT +58
#define SPECIES_ARCANINE_SPECIAL_TRAIT +59
#define SPECIES_POLIWAG_SPECIAL_TRAIT +60
#define SPECIES_POLIWHIRL_SPECIAL_TRAIT +61
#define SPECIES_POLIWRATH_SPECIAL_TRAIT +62
#define SPECIES_ABRA_SPECIAL_TRAIT +63
#define SPECIES_KADABRA_SPECIAL_TRAIT +64
#define SPECIES_ALAKAZAM_SPECIAL_TRAIT +65
#define SPECIES_MACHOP_SPECIAL_TRAIT +66
#define SPECIES_MACHOKE_SPECIAL_TRAIT +67
#define SPECIES_MACHAMP_SPECIAL_TRAIT +68
#define SPECIES_BELLSPROUT_SPECIAL_TRAIT +69
#define SPECIES_WEEPINBELL_SPECIAL_TRAIT +70
#define SPECIES_VICTREEBEL_SPECIAL_TRAIT +71
#define SPECIES_TENTACOOL_SPECIAL_TRAIT +72
#define SPECIES_TENTACRUEL_SPECIAL_TRAIT +73
#define SPECIES_GEODUDE_SPECIAL_TRAIT +74
#define SPECIES_GRAVELER_SPECIAL_TRAIT +75
#define SPECIES_GOLEM_SPECIAL_TRAIT +76
#define SPECIES_PONYTA_SPECIAL_TRAIT +77
#define SPECIES_RAPIDASH_SPECIAL_TRAIT +78
#define SPECIES_SLOWPOKE_SPECIAL_TRAIT +79
#define SPECIES_SLOWBRO_SPECIAL_TRAIT +80
#define SPECIES_MAGNEMITE_SPECIAL_TRAIT +81
#define SPECIES_MAGNETON_SPECIAL_TRAIT +82
#define SPECIES_FARFETCHD_SPECIAL_TRAIT +83
#define SPECIES_DODUO_SPECIAL_TRAIT +84
#define SPECIES_DODRIO_SPECIAL_TRAIT +85
#define SPECIES_SEEL_SPECIAL_TRAIT +86
#define SPECIES_DEWGONG_SPECIAL_TRAIT +87
#define SPECIES_GRIMER_SPECIAL_TRAIT +88
#define SPECIES_MUK_SPECIAL_TRAIT +89
#define SPECIES_SHELLDER_SPECIAL_TRAIT +90
#define SPECIES_CLOYSTER_SPECIAL_TRAIT +91
#define SPECIES_GASTLY_SPECIAL_TRAIT +92
#define SPECIES_HAUNTER_SPECIAL_TRAIT +93
#define SPECIES_GENGAR_SPECIAL_TRAIT +94
#define SPECIES_ONIX_SPECIAL_TRAIT +95
#define SPECIES_DROWZEE_SPECIAL_TRAIT +96
#define SPECIES_HYPNO_SPECIAL_TRAIT +97
#define SPECIES_KRABBY_SPECIAL_TRAIT +98
#define SPECIES_KINGLER_SPECIAL_TRAIT +99
#define SPECIES_VOLTORB_SPECIAL_TRAIT +100
#define SPECIES_ELECTRODE_SPECIAL_TRAIT +101
#define SPECIES_EXEGGCUTE_SPECIAL_TRAIT +102
#define SPECIES_EXEGGUTOR_SPECIAL_TRAIT +103
#define SPECIES_CUBONE_SPECIAL_TRAIT +104
#define SPECIES_MAROWAK_SPECIAL_TRAIT +105
#define SPECIES_HITMONLEE_SPECIAL_TRAIT +106
#define SPECIES_HITMONCHAN_SPECIAL_TRAIT +107
#define SPECIES_LICKITUNG_SPECIAL_TRAIT +108
#define SPECIES_KOFFING_SPECIAL_TRAIT +109
#define SPECIES_WEEZING_SPECIAL_TRAIT +110
#define SPECIES_RHYHORN_SPECIAL_TRAIT +111
#define SPECIES_RHYDON_SPECIAL_TRAIT +112
#define SPECIES_CHANSEY_SPECIAL_TRAIT +113
#define SPECIES_TANGELA_SPECIAL_TRAIT +114
#define SPECIES_KANGASKHAN_SPECIAL_TRAIT +115
#define SPECIES_HORSEA_SPECIAL_TRAIT +116
#define SPECIES_SEADRA_SPECIAL_TRAIT +117
#define SPECIES_GOLDEEN_SPECIAL_TRAIT +118
#define SPECIES_SEAKING_SPECIAL_TRAIT +119
#define SPECIES_STARYU_SPECIAL_TRAIT +120
#define SPECIES_STARMIE_SPECIAL_TRAIT +121
#define SPECIES_MR_MIME_SPECIAL_TRAIT +122
#define SPECIES_SCYTHER_SPECIAL_TRAIT +123
#define SPECIES_JYNX_SPECIAL_TRAIT +124
#define SPECIES_ELECTABUZZ_SPECIAL_TRAIT +125
#define SPECIES_MAGMAR_SPECIAL_TRAIT +126
#define SPECIES_PINSIR_SPECIAL_TRAIT +127
#define SPECIES_TAUROS_SPECIAL_TRAIT +128
#define SPECIES_MAGIKARP_SPECIAL_TRAIT +129
#define SPECIES_GYARADOS_SPECIAL_TRAIT +130
#define SPECIES_LAPRAS_SPECIAL_TRAIT +131
#define SPECIES_DITTO_SPECIAL_TRAIT +132
#define SPECIES_EEVEE_SPECIAL_TRAIT +133
#define SPECIES_VAPOREON_SPECIAL_TRAIT +134
#define SPECIES_JOLTEON_SPECIAL_TRAIT +135
#define SPECIES_FLAREON_SPECIAL_TRAIT +136
#define SPECIES_PORYGON_SPECIAL_TRAIT +137
#define SPECIES_OMANYTE_SPECIAL_TRAIT +138
#define SPECIES_OMASTAR_SPECIAL_TRAIT +139
#define SPECIES_KABUTO_SPECIAL_TRAIT +140
#define SPECIES_KABUTOPS_SPECIAL_TRAIT +141
#define SPECIES_AERODACTYL_SPECIAL_TRAIT +142
#define SPECIES_SNORLAX_SPECIAL_TRAIT +143
#define SPECIES_ARTICUNO_SPECIAL_TRAIT +144
#define SPECIES_ZAPDOS_SPECIAL_TRAIT +145
#define SPECIES_MOLTRES_SPECIAL_TRAIT +146
#define SPECIES_DRATINI_SPECIAL_TRAIT +147
#define SPECIES_DRAGONAIR_SPECIAL_TRAIT +148
#define SPECIES_DRAGONITE_SPECIAL_TRAIT +149
#define SPECIES_MEWTWO_SPECIAL_TRAIT +150
#define SPECIES_MEW_SPECIAL_TRAIT +151
#define SPECIES_CHIKORITA_SPECIAL_TRAIT +152
#define SPECIES_BAYLEEF_SPECIAL_TRAIT +153
#define SPECIES_MEGANIUM_SPECIAL_TRAIT +154
#define SPECIES_CYNDAQUIL_SPECIAL_TRAIT +155
#define SPECIES_QUILAVA_SPECIAL_TRAIT +156
#define SPECIES_TYPHLOSION_SPECIAL_TRAIT +157
#define SPECIES_TOTODILE_SPECIAL_TRAIT +158
#define SPECIES_CROCONAW_SPECIAL_TRAIT +159
#define SPECIES_FERALIGATR_SPECIAL_TRAIT +160
#define SPECIES_SENTRET_SPECIAL_TRAIT +161
#define SPECIES_FURRET_SPECIAL_TRAIT +162
#define SPECIES_HOOTHOOT_SPECIAL_TRAIT +163
#define SPECIES_NOCTOWL_SPECIAL_TRAIT +164
#define SPECIES_LEDYBA_SPECIAL_TRAIT +165
#define SPECIES_LEDIAN_SPECIAL_TRAIT +166
#define SPECIES_SPINARAK_SPECIAL_TRAIT +167
#define SPECIES_ARIADOS_SPECIAL_TRAIT +168
#define SPECIES_CROBAT_SPECIAL_TRAIT +169
#define SPECIES_CHINCHOU_SPECIAL_TRAIT +170
#define SPECIES_LANTURN_SPECIAL_TRAIT +171
#define SPECIES_PICHU_SPECIAL_TRAIT +172
#define SPECIES_CLEFFA_SPECIAL_TRAIT +173
#define SPECIES_IGGLYBUFF_SPECIAL_TRAIT +174
#define SPECIES_TOGEPI_SPECIAL_TRAIT +175
#define SPECIES_TOGETIC_SPECIAL_TRAIT +176
#define SPECIES_NATU_SPECIAL_TRAIT +177
#define SPECIES_XATU_SPECIAL_TRAIT +178
#define SPECIES_MAREEP_SPECIAL_TRAIT +179
#define SPECIES_FLAAFFY_SPECIAL_TRAIT +180
#define SPECIES_AMPHAROS_SPECIAL_TRAIT +181
#define SPECIES_BELLOSSOM_SPECIAL_TRAIT +182
#define SPECIES_MARILL_SPECIAL_TRAIT +183
#define SPECIES_AZUMARILL_SPECIAL_TRAIT +184
#define SPECIES_SUDOWOODO_SPECIAL_TRAIT +185
#define SPECIES_POLITOED_SPECIAL_TRAIT +186
#define SPECIES_HOPPIP_SPECIAL_TRAIT +187
#define SPECIES_SKIPLOOM_SPECIAL_TRAIT +188
#define SPECIES_JUMPLUFF_SPECIAL_TRAIT +189
#define SPECIES_AIPOM_SPECIAL_TRAIT +190
#define SPECIES_SUNKERN_SPECIAL_TRAIT +191
#define SPECIES_SUNFLORA_SPECIAL_TRAIT +192
#define SPECIES_YANMA_SPECIAL_TRAIT +193
#define SPECIES_WOOPER_SPECIAL_TRAIT +194
#define SPECIES_QUAGSIRE_SPECIAL_TRAIT +195
#define SPECIES_ESPEON_SPECIAL_TRAIT +196
#define SPECIES_UMBREON_SPECIAL_TRAIT +197
#define SPECIES_MURKROW_SPECIAL_TRAIT +198
#define SPECIES_SLOWKING_SPECIAL_TRAIT +199
#define SPECIES_MISDREAVUS_SPECIAL_TRAIT +200
#define SPECIES_UNOWN_SPECIAL_TRAIT +201
#define SPECIES_WOBBUFFET_SPECIAL_TRAIT +202
#define SPECIES_GIRAFARIG_SPECIAL_TRAIT +203
#define SPECIES_PINECO_SPECIAL_TRAIT +204
#define SPECIES_FORRETRESS_SPECIAL_TRAIT +205
#define SPECIES_DUNSPARCE_SPECIAL_TRAIT +206
#define SPECIES_GLIGAR_SPECIAL_TRAIT +207
#define SPECIES_STEELIX_SPECIAL_TRAIT +208
#define SPECIES_SNUBBULL_SPECIAL_TRAIT +209
#define SPECIES_GRANBULL_SPECIAL_TRAIT +210
#define SPECIES_QWILFISH_SPECIAL_TRAIT +211
#define SPECIES_SCIZOR_SPECIAL_TRAIT +212
#define SPECIES_SHUCKLE_SPECIAL_TRAIT +213
#define SPECIES_HERACROSS_SPECIAL_TRAIT +214
#define SPECIES_SNEASEL_SPECIAL_TRAIT +215
#define SPECIES_TEDDIURSA_SPECIAL_TRAIT +216
#define SPECIES_URSARING_SPECIAL_TRAIT +217
#define SPECIES_SLUGMA_SPECIAL_TRAIT +218
#define SPECIES_MAGCARGO_SPECIAL_TRAIT +219
#define SPECIES_SWINUB_SPECIAL_TRAIT +220
#define SPECIES_PILOSWINE_SPECIAL_TRAIT +221
#define SPECIES_CORSOLA_SPECIAL_TRAIT +222
#define SPECIES_REMORAID_SPECIAL_TRAIT +223
#define SPECIES_OCTILLERY_SPECIAL_TRAIT +224
#define SPECIES_DELIBIRD_SPECIAL_TRAIT +225
#define SPECIES_MANTINE_SPECIAL_TRAIT +226
#define SPECIES_SKARMORY_SPECIAL_TRAIT +227
#define SPECIES_HOUNDOUR_SPECIAL_TRAIT +228
#define SPECIES_HOUNDOOM_SPECIAL_TRAIT +229
#define SPECIES_KINGDRA_SPECIAL_TRAIT +230
#define SPECIES_PHANPY_SPECIAL_TRAIT +231
#define SPECIES_DONPHAN_SPECIAL_TRAIT +232
#define SPECIES_PORYGON2_SPECIAL_TRAIT +233
#define SPECIES_STANTLER_SPECIAL_TRAIT +234
#define SPECIES_SMEARGLE_SPECIAL_TRAIT +235
#define SPECIES_TYROGUE_SPECIAL_TRAIT +236
#define SPECIES_HITMONTOP_SPECIAL_TRAIT +237
#define SPECIES_SMOOCHUM_SPECIAL_TRAIT +238
#define SPECIES_ELEKID_SPECIAL_TRAIT +239
#define SPECIES_MAGBY_SPECIAL_TRAIT +240
#define SPECIES_MILTANK_SPECIAL_TRAIT +241
#define SPECIES_BLISSEY_SPECIAL_TRAIT +242
#define SPECIES_RAIKOU_SPECIAL_TRAIT +243
#define SPECIES_ENTEI_SPECIAL_TRAIT +244
#define SPECIES_SUICUNE_SPECIAL_TRAIT +245
#define SPECIES_LARVITAR_SPECIAL_TRAIT +246
#define SPECIES_PUPITAR_SPECIAL_TRAIT +247
#define SPECIES_TYRANITAR_SPECIAL_TRAIT +248
#define SPECIES_LUGIA_SPECIAL_TRAIT +249
#define SPECIES_HO_OH_SPECIAL_TRAIT +250
#define SPECIES_CELEBI_SPECIAL_TRAIT +251
#define SPECIES_TREECKO_SPECIAL_TRAIT +252
#define SPECIES_GROVYLE_SPECIAL_TRAIT +253
#define SPECIES_SCEPTILE_SPECIAL_TRAIT +254
#define SPECIES_TORCHIC_SPECIAL_TRAIT +255
#define SPECIES_COMBUSKEN_SPECIAL_TRAIT +256
#define SPECIES_BLAZIKEN_SPECIAL_TRAIT +257
#define SPECIES_MUDKIP_SPECIAL_TRAIT +258
#define SPECIES_MARSHTOMP_SPECIAL_TRAIT +259
#define SPECIES_SWAMPERT_SPECIAL_TRAIT +260
#define SPECIES_POOCHYENA_SPECIAL_TRAIT +261
#define SPECIES_MIGHTYENA_SPECIAL_TRAIT +262
#define SPECIES_ZIGZAGOON_SPECIAL_TRAIT +263
#define SPECIES_LINOONE_SPECIAL_TRAIT +264
#define SPECIES_WURMPLE_SPECIAL_TRAIT +265
#define SPECIES_SILCOON_SPECIAL_TRAIT +266
#define SPECIES_BEAUTIFLY_SPECIAL_TRAIT +267
#define SPECIES_CASCOON_SPECIAL_TRAIT +268
#define SPECIES_DUSTOX_SPECIAL_TRAIT +269
#define SPECIES_LOTAD_SPECIAL_TRAIT +270
#define SPECIES_LOMBRE_SPECIAL_TRAIT +271
#define SPECIES_LUDICOLO_SPECIAL_TRAIT +272
#define SPECIES_SEEDOT_SPECIAL_TRAIT +273
#define SPECIES_NUZLEAF_SPECIAL_TRAIT +274
#define SPECIES_SHIFTRY_SPECIAL_TRAIT +275
#define SPECIES_TAILLOW_SPECIAL_TRAIT +276
#define SPECIES_SWELLOW_SPECIAL_TRAIT +277
#define SPECIES_WINGULL_SPECIAL_TRAIT +278
#define SPECIES_PELIPPER_SPECIAL_TRAIT +279
#define SPECIES_RALTS_SPECIAL_TRAIT +280
#define SPECIES_KIRLIA_SPECIAL_TRAIT +281
#define SPECIES_GARDEVOIR_SPECIAL_TRAIT +282
#define SPECIES_SURSKIT_SPECIAL_TRAIT +283
#define SPECIES_MASQUERAIN_SPECIAL_TRAIT +284
#define SPECIES_SHROOMISH_SPECIAL_TRAIT +285
#define SPECIES_BRELOOM_SPECIAL_TRAIT +286
#define SPECIES_SLAKOTH_SPECIAL_TRAIT +287
#define SPECIES_VIGOROTH_SPECIAL_TRAIT +288
#define SPECIES_SLAKING_SPECIAL_TRAIT +289
#define SPECIES_NINCADA_SPECIAL_TRAIT +290
#define SPECIES_NINJASK_SPECIAL_TRAIT +291
#define SPECIES_SHEDINJA_SPECIAL_TRAIT +292
#define SPECIES_WHISMUR_SPECIAL_TRAIT +293
#define SPECIES_LOUDRED_SPECIAL_TRAIT +294
#define SPECIES_EXPLOUD_SPECIAL_TRAIT +295
#define SPECIES_MAKUHITA_SPECIAL_TRAIT +296
#define SPECIES_HARIYAMA_SPECIAL_TRAIT +297
#define SPECIES_AZURILL_SPECIAL_TRAIT +298
#define SPECIES_NOSEPASS_SPECIAL_TRAIT +299
#define SPECIES_SKITTY_SPECIAL_TRAIT +300
#define SPECIES_DELCATTY_SPECIAL_TRAIT +301
#define SPECIES_SABLEYE_SPECIAL_TRAIT +302
#define SPECIES_MAWILE_SPECIAL_TRAIT +303
#define SPECIES_ARON_SPECIAL_TRAIT +304
#define SPECIES_LAIRON_SPECIAL_TRAIT +305
#define SPECIES_AGGRON_SPECIAL_TRAIT +306
#define SPECIES_MEDITITE_SPECIAL_TRAIT +307
#define SPECIES_MEDICHAM_SPECIAL_TRAIT +308
#define SPECIES_ELECTRIKE_SPECIAL_TRAIT +309
#define SPECIES_MANECTRIC_SPECIAL_TRAIT +310
#define SPECIES_PLUSLE_SPECIAL_TRAIT +311
#define SPECIES_MINUN_SPECIAL_TRAIT +312
#define SPECIES_VOLBEAT_SPECIAL_TRAIT +313
#define SPECIES_ILLUMISE_SPECIAL_TRAIT +314
#define SPECIES_ROSELIA_SPECIAL_TRAIT +315
#define SPECIES_GULPIN_SPECIAL_TRAIT +316
#define SPECIES_SWALOT_SPECIAL_TRAIT +317
#define SPECIES_CARVANHA_SPECIAL_TRAIT +318
#define SPECIES_SHARPEDO_SPECIAL_TRAIT +319
#define SPECIES_WAILMER_SPECIAL_TRAIT +320
#define SPECIES_WAILORD_SPECIAL_TRAIT +321
#define SPECIES_NUMEL_SPECIAL_TRAIT +322
#define SPECIES_CAMERUPT_SPECIAL_TRAIT +323
#define SPECIES_TORKOAL_SPECIAL_TRAIT +324
#define SPECIES_SPOINK_SPECIAL_TRAIT +325
#define SPECIES_GRUMPIG_SPECIAL_TRAIT +326
#define SPECIES_SPINDA_SPECIAL_TRAIT +327
#define SPECIES_TRAPINCH_SPECIAL_TRAIT +328
#define SPECIES_VIBRAVA_SPECIAL_TRAIT +329
#define SPECIES_FLYGON_SPECIAL_TRAIT +330
#define SPECIES_CACNEA_SPECIAL_TRAIT +331
#define SPECIES_CACTURNE_SPECIAL_TRAIT +332
#define SPECIES_SWABLU_SPECIAL_TRAIT +333
#define SPECIES_ALTARIA_SPECIAL_TRAIT +334
#define SPECIES_ZANGOOSE_SPECIAL_TRAIT +335
#define SPECIES_SEVIPER_SPECIAL_TRAIT +336
#define SPECIES_LUNATONE_SPECIAL_TRAIT +337
#define SPECIES_SOLROCK_SPECIAL_TRAIT +338
#define SPECIES_BARBOACH_SPECIAL_TRAIT +339
#define SPECIES_WHISCASH_SPECIAL_TRAIT +340
#define SPECIES_CORPHISH_SPECIAL_TRAIT +341
#define SPECIES_CRAWDAUNT_SPECIAL_TRAIT +342
#define SPECIES_BALTOY_SPECIAL_TRAIT +343
#define SPECIES_CLAYDOL_SPECIAL_TRAIT +344
#define SPECIES_LILEEP_SPECIAL_TRAIT +345
#define SPECIES_CRADILY_SPECIAL_TRAIT +346
#define SPECIES_ANORITH_SPECIAL_TRAIT +347
#define SPECIES_ARMALDO_SPECIAL_TRAIT +348
#define SPECIES_FEEBAS_SPECIAL_TRAIT +349
#define SPECIES_MILOTIC_SPECIAL_TRAIT +350
#define SPECIES_CASTFORM_SPECIAL_TRAIT +351
#define SPECIES_KECLEON_SPECIAL_TRAIT +352
#define SPECIES_SHUPPET_SPECIAL_TRAIT +353
#define SPECIES_BANETTE_SPECIAL_TRAIT +354
#define SPECIES_DUSKULL_SPECIAL_TRAIT +355
#define SPECIES_DUSCLOPS_SPECIAL_TRAIT +356
#define SPECIES_TROPIUS_SPECIAL_TRAIT +357
#define SPECIES_CHIMECHO_SPECIAL_TRAIT +358
#define SPECIES_ABSOL_SPECIAL_TRAIT +359
#define SPECIES_WYNAUT_SPECIAL_TRAIT +360
#define SPECIES_SNORUNT_SPECIAL_TRAIT +361
#define SPECIES_GLALIE_SPECIAL_TRAIT +362
#define SPECIES_SPHEAL_SPECIAL_TRAIT +363
#define SPECIES_SEALEO_SPECIAL_TRAIT +364
#define SPECIES_WALREIN_SPECIAL_TRAIT +365
#define SPECIES_CLAMPERL_SPECIAL_TRAIT +366
#define SPECIES_HUNTAIL_SPECIAL_TRAIT +367
#define SPECIES_GOREBYSS_SPECIAL_TRAIT +368
#define SPECIES_RELICANTH_SPECIAL_TRAIT +369
#define SPECIES_LUVDISC_SPECIAL_TRAIT +370
#define SPECIES_BAGON_SPECIAL_TRAIT +371
#define SPECIES_SHELGON_SPECIAL_TRAIT +372
#define SPECIES_SALAMENCE_SPECIAL_TRAIT +373
#define SPECIES_BELDUM_SPECIAL_TRAIT +374
#define SPECIES_METANG_SPECIAL_TRAIT +375
#define SPECIES_METAGROSS_SPECIAL_TRAIT +376
#define SPECIES_REGIROCK_SPECIAL_TRAIT +377
#define SPECIES_REGICE_SPECIAL_TRAIT +378
#define SPECIES_REGISTEEL_SPECIAL_TRAIT +379
#define SPECIES_LATIAS_SPECIAL_TRAIT +380
#define SPECIES_LATIOS_SPECIAL_TRAIT +381
#define SPECIES_KYOGRE_SPECIAL_TRAIT +382
#define SPECIES_GROUDON_SPECIAL_TRAIT +383
#define SPECIES_RAYQUAZA_SPECIAL_TRAIT +384
#define SPECIES_JIRACHI_SPECIAL_TRAIT +385
#define SPECIES_DEOXYS_SPECIAL_TRAIT +386
#define SPECIES_TURTWIG_SPECIAL_TRAIT +387
#define SPECIES_GROTLE_SPECIAL_TRAIT +388
#define SPECIES_TORTERRA_SPECIAL_TRAIT +389
#define SPECIES_CHIMCHAR_SPECIAL_TRAIT +390
#define SPECIES_MONFERNO_SPECIAL_TRAIT +391
#define SPECIES_INFERNAPE_SPECIAL_TRAIT +392
#define SPECIES_PIPLUP_SPECIAL_TRAIT +393
#define SPECIES_PRINPLUP_SPECIAL_TRAIT +394
#define SPECIES_EMPOLEON_SPECIAL_TRAIT +395
#define SPECIES_STARLY_SPECIAL_TRAIT +396
#define SPECIES_STARAVIA_SPECIAL_TRAIT +397
#define SPECIES_STARAPTOR_SPECIAL_TRAIT +398
#define SPECIES_BIDOOF_SPECIAL_TRAIT +399
#define SPECIES_BIBAREL_SPECIAL_TRAIT +400
#define SPECIES_KRICKETOT_SPECIAL_TRAIT +401
#define SPECIES_KRICKETUNE_SPECIAL_TRAIT +402
#define SPECIES_SHINX_SPECIAL_TRAIT +403
#define SPECIES_LUXIO_SPECIAL_TRAIT +404
#define SPECIES_LUXRAY_SPECIAL_TRAIT +405
#define SPECIES_BUDEW_SPECIAL_TRAIT +406
#define SPECIES_ROSERADE_SPECIAL_TRAIT +407
#define SPECIES_CRANIDOS_SPECIAL_TRAIT +408
#define SPECIES_RAMPARDOS_SPECIAL_TRAIT +409
#define SPECIES_SHIELDON_SPECIAL_TRAIT +410
#define SPECIES_BASTIODON_SPECIAL_TRAIT +411
#define SPECIES_BURMY_SPECIAL_TRAIT +412
#define SPECIES_WORMADAM_SPECIAL_TRAIT +413
#define SPECIES_MOTHIM_SPECIAL_TRAIT +414
#define SPECIES_COMBEE_SPECIAL_TRAIT +415
#define SPECIES_VESPIQUEN_SPECIAL_TRAIT +416
#define SPECIES_PACHIRISU_SPECIAL_TRAIT +417
#define SPECIES_BUIZEL_SPECIAL_TRAIT +418
#define SPECIES_FLOATZEL_SPECIAL_TRAIT +419
#define SPECIES_CHERUBI_SPECIAL_TRAIT +420
#define SPECIES_CHERRIM_SPECIAL_TRAIT +421
#define SPECIES_SHELLOS_SPECIAL_TRAIT +422
#define SPECIES_GASTRODON_SPECIAL_TRAIT +423
#define SPECIES_AMBIPOM_SPECIAL_TRAIT +424
#define SPECIES_DRIFLOON_SPECIAL_TRAIT +425
#define SPECIES_DRIFBLIM_SPECIAL_TRAIT +426
#define SPECIES_BUNEARY_SPECIAL_TRAIT +427
#define SPECIES_LOPUNNY_SPECIAL_TRAIT +428
#define SPECIES_MISMAGIUS_SPECIAL_TRAIT +429
#define SPECIES_HONCHKROW_SPECIAL_TRAIT +430
#define SPECIES_GLAMEOW_SPECIAL_TRAIT +431
#define SPECIES_PURUGLY_SPECIAL_TRAIT +432
#define SPECIES_CHINGLING_SPECIAL_TRAIT +433
#define SPECIES_STUNKY_SPECIAL_TRAIT +434
#define SPECIES_SKUNTANK_SPECIAL_TRAIT +435
#define SPECIES_BRONZOR_SPECIAL_TRAIT +436
#define SPECIES_BRONZONG_SPECIAL_TRAIT +437
#define SPECIES_BONSLY_SPECIAL_TRAIT +438
#define SPECIES_MIME_JR_SPECIAL_TRAIT +439
#define SPECIES_HAPPINY_SPECIAL_TRAIT +440
#define SPECIES_CHATOT_SPECIAL_TRAIT +441
#define SPECIES_SPIRITOMB_SPECIAL_TRAIT +442
#define SPECIES_GIBLE_SPECIAL_TRAIT +443
#define SPECIES_GABITE_SPECIAL_TRAIT +444
#define SPECIES_GARCHOMP_SPECIAL_TRAIT +445
#define SPECIES_MUNCHLAX_SPECIAL_TRAIT +446
#define SPECIES_RIOLU_SPECIAL_TRAIT +447
#define SPECIES_LUCARIO_SPECIAL_TRAIT +448
#define SPECIES_HIPPOPOTAS_SPECIAL_TRAIT +449
#define SPECIES_HIPPOWDON_SPECIAL_TRAIT +450
#define SPECIES_SKORUPI_SPECIAL_TRAIT +451
#define SPECIES_DRAPION_SPECIAL_TRAIT +452
#define SPECIES_CROAGUNK_SPECIAL_TRAIT +453
#define SPECIES_TOXICROAK_SPECIAL_TRAIT +454
#define SPECIES_CARNIVINE_SPECIAL_TRAIT +455
#define SPECIES_FINNEON_SPECIAL_TRAIT +456
#define SPECIES_LUMINEON_SPECIAL_TRAIT +457
#define SPECIES_MANTYKE_SPECIAL_TRAIT +458
#define SPECIES_SNOVER_SPECIAL_TRAIT +459
#define SPECIES_ABOMASNOW_SPECIAL_TRAIT +460
#define SPECIES_WEAVILE_SPECIAL_TRAIT +461
#define SPECIES_MAGNEZONE_SPECIAL_TRAIT +462
#define SPECIES_LICKILICKY_SPECIAL_TRAIT +463
#define SPECIES_RHYPERIOR_SPECIAL_TRAIT +464
#define SPECIES_TANGROWTH_SPECIAL_TRAIT +465
#define SPECIES_ELECTIVIRE_SPECIAL_TRAIT +466
#define SPECIES_MAGMORTAR_SPECIAL_TRAIT +467
#define SPECIES_TOGEKISS_SPECIAL_TRAIT +468
#define SPECIES_YANMEGA_SPECIAL_TRAIT +469
#define SPECIES_LEAFEON_SPECIAL_TRAIT +470
#define SPECIES_GLACEON_SPECIAL_TRAIT +471
#define SPECIES_GLISCOR_SPECIAL_TRAIT +472
#define SPECIES_MAMOSWINE_SPECIAL_TRAIT +473
#define SPECIES_PORYGON_Z_SPECIAL_TRAIT +474
#define SPECIES_GALLADE_SPECIAL_TRAIT +475
#define SPECIES_PROBOPASS_SPECIAL_TRAIT +476
#define SPECIES_DUSKNOIR_SPECIAL_TRAIT +477
#define SPECIES_FROSLASS_SPECIAL_TRAIT +478
#define SPECIES_ROTOM_SPECIAL_TRAIT +479
#define SPECIES_UXIE_SPECIAL_TRAIT +480
#define SPECIES_MESPRIT_SPECIAL_TRAIT +481
#define SPECIES_AZELF_SPECIAL_TRAIT +482
#define SPECIES_DIALGA_SPECIAL_TRAIT +483
#define SPECIES_PALKIA_SPECIAL_TRAIT +484
#define SPECIES_HEATRAN_SPECIAL_TRAIT +485
#define SPECIES_REGIGIGAS_SPECIAL_TRAIT +486
#define SPECIES_GIRATINA_SPECIAL_TRAIT +487
#define SPECIES_CRESSELIA_SPECIAL_TRAIT +488
#define SPECIES_PHIONE_SPECIAL_TRAIT +489
#define SPECIES_MANAPHY_SPECIAL_TRAIT +490
#define SPECIES_DARKRAI_SPECIAL_TRAIT +491
#define SPECIES_SHAYMIN_SPECIAL_TRAIT +492
#define SPECIES_ARCEUS_SPECIAL_TRAIT +493
#define SPECIES_VICTINI_SPECIAL_TRAIT +494
#define SPECIES_SNIVY_SPECIAL_TRAIT +495
#define SPECIES_SERVINE_SPECIAL_TRAIT +496
#define SPECIES_SERPERIOR_SPECIAL_TRAIT +497
#define SPECIES_TEPIG_SPECIAL_TRAIT +498
#define SPECIES_PIGNITE_SPECIAL_TRAIT +499
#define SPECIES_EMBOAR_SPECIAL_TRAIT +500
#define SPECIES_OSHAWOTT_SPECIAL_TRAIT +501
#define SPECIES_DEWOTT_SPECIAL_TRAIT +502
#define SPECIES_SAMUROTT_SPECIAL_TRAIT +503
#define SPECIES_PATRAT_SPECIAL_TRAIT +504
#define SPECIES_WATCHOG_SPECIAL_TRAIT +505
#define SPECIES_LILLIPUP_SPECIAL_TRAIT +506
#define SPECIES_HERDIER_SPECIAL_TRAIT +507
#define SPECIES_STOUTLAND_SPECIAL_TRAIT +508
#define SPECIES_PURRLOIN_SPECIAL_TRAIT +509
#define SPECIES_LIEPARD_SPECIAL_TRAIT +510
#define SPECIES_PANSAGE_SPECIAL_TRAIT +511
#define SPECIES_SIMISAGE_SPECIAL_TRAIT +512
#define SPECIES_PANSEAR_SPECIAL_TRAIT +513
#define SPECIES_SIMISEAR_SPECIAL_TRAIT +514
#define SPECIES_PANPOUR_SPECIAL_TRAIT +515
#define SPECIES_SIMIPOUR_SPECIAL_TRAIT +516
#define SPECIES_MUNNA_SPECIAL_TRAIT +517
#define SPECIES_MUSHARNA_SPECIAL_TRAIT +518
#define SPECIES_PIDOVE_SPECIAL_TRAIT +519
#define SPECIES_TRANQUILL_SPECIAL_TRAIT +520
#define SPECIES_UNFEZANT_SPECIAL_TRAIT +521
#define SPECIES_BLITZLE_SPECIAL_TRAIT +522
#define SPECIES_ZEBSTRIKA_SPECIAL_TRAIT +523
#define SPECIES_ROGGENROLA_SPECIAL_TRAIT +524
#define SPECIES_BOLDORE_SPECIAL_TRAIT +525
#define SPECIES_GIGALITH_SPECIAL_TRAIT +526
#define SPECIES_WOOBAT_SPECIAL_TRAIT +527
#define SPECIES_SWOOBAT_SPECIAL_TRAIT +528
#define SPECIES_DRILBUR_SPECIAL_TRAIT +529
#define SPECIES_EXCADRILL_SPECIAL_TRAIT +530
#define SPECIES_AUDINO_SPECIAL_TRAIT +531
#define SPECIES_TIMBURR_SPECIAL_TRAIT +532
#define SPECIES_GURDURR_SPECIAL_TRAIT +533
#define SPECIES_CONKELDURR_SPECIAL_TRAIT +534
#define SPECIES_TYMPOLE_SPECIAL_TRAIT +535
#define SPECIES_PALPITOAD_SPECIAL_TRAIT +536
#define SPECIES_SEISMITOAD_SPECIAL_TRAIT +537
#define SPECIES_THROH_SPECIAL_TRAIT +538
#define SPECIES_SAWK_SPECIAL_TRAIT +539
#define SPECIES_SEWADDLE_SPECIAL_TRAIT +540
#define SPECIES_SWADLOON_SPECIAL_TRAIT +541
#define SPECIES_LEAVANNY_SPECIAL_TRAIT +542
#define SPECIES_VENIPEDE_SPECIAL_TRAIT +543
#define SPECIES_WHIRLIPEDE_SPECIAL_TRAIT +544
#define SPECIES_SCOLIPEDE_SPECIAL_TRAIT +545
#define SPECIES_COTTONEE_SPECIAL_TRAIT +546
#define SPECIES_WHIMSICOTT_SPECIAL_TRAIT +547
#define SPECIES_PETILIL_SPECIAL_TRAIT +548
#define SPECIES_LILLIGANT_SPECIAL_TRAIT +549
#define SPECIES_BASCULIN_SPECIAL_TRAIT +550
#define SPECIES_SANDILE_SPECIAL_TRAIT +551
#define SPECIES_KROKOROK_SPECIAL_TRAIT +552
#define SPECIES_KROOKODILE_SPECIAL_TRAIT +553
#define SPECIES_DARUMAKA_SPECIAL_TRAIT +554
#define SPECIES_DARMANITAN_SPECIAL_TRAIT +555
#define SPECIES_MARACTUS_SPECIAL_TRAIT +556
#define SPECIES_DWEBBLE_SPECIAL_TRAIT +557
#define SPECIES_CRUSTLE_SPECIAL_TRAIT +558
#define SPECIES_SCRAGGY_SPECIAL_TRAIT +559
#define SPECIES_SCRAFTY_SPECIAL_TRAIT +560
#define SPECIES_SIGILYPH_SPECIAL_TRAIT +561
#define SPECIES_YAMASK_SPECIAL_TRAIT +562
#define SPECIES_COFAGRIGUS_SPECIAL_TRAIT +563
#define SPECIES_TIRTOUGA_SPECIAL_TRAIT +564
#define SPECIES_CARRACOSTA_SPECIAL_TRAIT +565
#define SPECIES_ARCHEN_SPECIAL_TRAIT +566
#define SPECIES_ARCHEOPS_SPECIAL_TRAIT +567
#define SPECIES_TRUBBISH_SPECIAL_TRAIT +568
#define SPECIES_GARBODOR_SPECIAL_TRAIT +569
#define SPECIES_ZORUA_SPECIAL_TRAIT +570
#define SPECIES_ZOROARK_SPECIAL_TRAIT +571
#define SPECIES_MINCCINO_SPECIAL_TRAIT +572
#define SPECIES_CINCCINO_SPECIAL_TRAIT +573
#define SPECIES_GOTHITA_SPECIAL_TRAIT +574
#define SPECIES_GOTHORITA_SPECIAL_TRAIT +575
#define SPECIES_GOTHITELLE_SPECIAL_TRAIT +576
#define SPECIES_SOLOSIS_SPECIAL_TRAIT +577
#define SPECIES_DUOSION_SPECIAL_TRAIT +578
#define SPECIES_REUNICLUS_SPECIAL_TRAIT +579
#define SPECIES_DUCKLETT_SPECIAL_TRAIT +580
#define SPECIES_SWANNA_SPECIAL_TRAIT +581
#define SPECIES_VANILLITE_SPECIAL_TRAIT +582
#define SPECIES_VANILLISH_SPECIAL_TRAIT +583
#define SPECIES_VANILLUXE_SPECIAL_TRAIT +584
#define SPECIES_DEERLING_SPECIAL_TRAIT +585
#define SPECIES_SAWSBUCK_SPECIAL_TRAIT +586
#define SPECIES_EMOLGA_SPECIAL_TRAIT +587
#define SPECIES_KARRABLAST_SPECIAL_TRAIT +588
#define SPECIES_ESCAVALIER_SPECIAL_TRAIT +589
#define SPECIES_FOONGUS_SPECIAL_TRAIT +590
#define SPECIES_AMOONGUSS_SPECIAL_TRAIT +591
#define SPECIES_FRILLISH_SPECIAL_TRAIT +592
#define SPECIES_JELLICENT_SPECIAL_TRAIT +593
#define SPECIES_ALOMOMOLA_SPECIAL_TRAIT +594
#define SPECIES_JOLTIK_SPECIAL_TRAIT +595
#define SPECIES_GALVANTULA_SPECIAL_TRAIT +596
#define SPECIES_FERROSEED_SPECIAL_TRAIT +597
#define SPECIES_FERROTHORN_SPECIAL_TRAIT +598
#define SPECIES_KLINK_SPECIAL_TRAIT +599
#define SPECIES_KLANG_SPECIAL_TRAIT +600
#define SPECIES_KLINKLANG_SPECIAL_TRAIT +601
#define SPECIES_TYNAMO_SPECIAL_TRAIT +602
#define SPECIES_EELEKTRIK_SPECIAL_TRAIT +603
#define SPECIES_EELEKTROSS_SPECIAL_TRAIT +604
#define SPECIES_ELGYEM_SPECIAL_TRAIT +605
#define SPECIES_BEHEEYEM_SPECIAL_TRAIT +606
#define SPECIES_LITWICK_SPECIAL_TRAIT +607
#define SPECIES_LAMPENT_SPECIAL_TRAIT +608
#define SPECIES_CHANDELURE_SPECIAL_TRAIT +609
#define SPECIES_AXEW_SPECIAL_TRAIT +610
#define SPECIES_FRAXURE_SPECIAL_TRAIT +611
#define SPECIES_HAXORUS_SPECIAL_TRAIT +612
#define SPECIES_CUBCHOO_SPECIAL_TRAIT +613
#define SPECIES_BEARTIC_SPECIAL_TRAIT +614
#define SPECIES_CRYOGONAL_SPECIAL_TRAIT +615
#define SPECIES_SHELMET_SPECIAL_TRAIT +616
#define SPECIES_ACCELGOR_SPECIAL_TRAIT +617
#define SPECIES_STUNFISK_SPECIAL_TRAIT +618
#define SPECIES_MIENFOO_SPECIAL_TRAIT +619
#define SPECIES_MIENSHAO_SPECIAL_TRAIT +620
#define SPECIES_DRUDDIGON_SPECIAL_TRAIT +621
#define SPECIES_GOLETT_SPECIAL_TRAIT +622
#define SPECIES_GOLURK_SPECIAL_TRAIT +623
#define SPECIES_PAWNIARD_SPECIAL_TRAIT +624
#define SPECIES_BISHARP_SPECIAL_TRAIT +625
#define SPECIES_BOUFFALANT_SPECIAL_TRAIT +626
#define SPECIES_RUFFLET_SPECIAL_TRAIT +627
#define SPECIES_BRAVIARY_SPECIAL_TRAIT +628
#define SPECIES_VULLABY_SPECIAL_TRAIT +629
#define SPECIES_MANDIBUZZ_SPECIAL_TRAIT +630
#define SPECIES_HEATMOR_SPECIAL_TRAIT +631
#define SPECIES_DURANT_SPECIAL_TRAIT +632
#define SPECIES_DEINO_SPECIAL_TRAIT +633
#define SPECIES_ZWEILOUS_SPECIAL_TRAIT +634
#define SPECIES_HYDREIGON_SPECIAL_TRAIT +635
#define SPECIES_LARVESTA_SPECIAL_TRAIT +636
#define SPECIES_VOLCARONA_SPECIAL_TRAIT +637
#define SPECIES_COBALION_SPECIAL_TRAIT +638
#define SPECIES_TERRAKION_SPECIAL_TRAIT +639
#define SPECIES_VIRIZION_SPECIAL_TRAIT +640
#define SPECIES_TORNADUS_SPECIAL_TRAIT +641
#define SPECIES_THUNDURUS_SPECIAL_TRAIT +642
#define SPECIES_RESHIRAM_SPECIAL_TRAIT +643
#define SPECIES_ZEKROM_SPECIAL_TRAIT +644
#define SPECIES_LANDORUS_SPECIAL_TRAIT +645
#define SPECIES_KYUREM_SPECIAL_TRAIT +646
#define SPECIES_KELDEO_SPECIAL_TRAIT +647
#define SPECIES_MELOETTA_SPECIAL_TRAIT +648
#define SPECIES_GENESECT_SPECIAL_TRAIT +649
#define SPECIES_CHESPIN_SPECIAL_TRAIT +650
#define SPECIES_QUILLADIN_SPECIAL_TRAIT +651
#define SPECIES_CHESNAUGHT_SPECIAL_TRAIT +652
#define SPECIES_FENNEKIN_SPECIAL_TRAIT +653
#define SPECIES_BRAIXEN_SPECIAL_TRAIT +654
#define SPECIES_DELPHOX_SPECIAL_TRAIT +655
#define SPECIES_FROAKIE_SPECIAL_TRAIT +656
#define SPECIES_FROGADIER_SPECIAL_TRAIT +657
#define SPECIES_GRENINJA_SPECIAL_TRAIT +658
#define SPECIES_BUNNELBY_SPECIAL_TRAIT +659
#define SPECIES_DIGGERSBY_SPECIAL_TRAIT +660
#define SPECIES_FLETCHLING_SPECIAL_TRAIT +661
#define SPECIES_FLETCHINDER_SPECIAL_TRAIT +662
#define SPECIES_TALONFLAME_SPECIAL_TRAIT +663
#define SPECIES_SCATTERBUG_SPECIAL_TRAIT +664
#define SPECIES_SPEWPA_SPECIAL_TRAIT +665
#define SPECIES_VIVILLON_SPECIAL_TRAIT +666 // Icy Snow Pattern
#define SPECIES_LITLEO_SPECIAL_TRAIT +667
#define SPECIES_PYROAR_SPECIAL_TRAIT +668
#define SPECIES_FLABEBE_SPECIAL_TRAIT +669 // Red Flower
#define SPECIES_FLOETTE_SPECIAL_TRAIT +670
#define SPECIES_FLORGES_SPECIAL_TRAIT +671
#define SPECIES_SKIDDO_SPECIAL_TRAIT +672
#define SPECIES_GOGOAT_SPECIAL_TRAIT +673
#define SPECIES_PANCHAM_SPECIAL_TRAIT +674
#define SPECIES_PANGORO_SPECIAL_TRAIT +675
#define SPECIES_FURFROU_SPECIAL_TRAIT +676
#define SPECIES_ESPURR_SPECIAL_TRAIT +677
#define SPECIES_MEOWSTIC_SPECIAL_TRAIT +678
#define SPECIES_HONEDGE_SPECIAL_TRAIT +679
#define SPECIES_DOUBLADE_SPECIAL_TRAIT +680
#define SPECIES_AEGISLASH_SPECIAL_TRAIT +681
#define SPECIES_SPRITZEE_SPECIAL_TRAIT +682
#define SPECIES_AROMATISSE_SPECIAL_TRAIT +683
#define SPECIES_SWIRLIX_SPECIAL_TRAIT +684
#define SPECIES_SLURPUFF_SPECIAL_TRAIT +685
#define SPECIES_INKAY_SPECIAL_TRAIT +686
#define SPECIES_MALAMAR_SPECIAL_TRAIT +687
#define SPECIES_BINACLE_SPECIAL_TRAIT +688
#define SPECIES_BARBARACLE_SPECIAL_TRAIT +689
#define SPECIES_SKRELP_SPECIAL_TRAIT +690
#define SPECIES_DRAGALGE_SPECIAL_TRAIT +691
#define SPECIES_CLAUNCHER_SPECIAL_TRAIT +692
#define SPECIES_CLAWITZER_SPECIAL_TRAIT +693
#define SPECIES_HELIOPTILE_SPECIAL_TRAIT +694
#define SPECIES_HELIOLISK_SPECIAL_TRAIT +695
#define SPECIES_TYRUNT_SPECIAL_TRAIT +696
#define SPECIES_TYRANTRUM_SPECIAL_TRAIT +697
#define SPECIES_AMAURA_SPECIAL_TRAIT +698
#define SPECIES_AURORUS_SPECIAL_TRAIT +699
#define SPECIES_SYLVEON_SPECIAL_TRAIT +700
#define SPECIES_HAWLUCHA_SPECIAL_TRAIT +701
#define SPECIES_DEDENNE_SPECIAL_TRAIT +702
#define SPECIES_CARBINK_SPECIAL_TRAIT +703
#define SPECIES_GOOMY_SPECIAL_TRAIT +704
#define SPECIES_SLIGGOO_SPECIAL_TRAIT +705
#define SPECIES_GOODRA_SPECIAL_TRAIT +706
#define SPECIES_KLEFKI_SPECIAL_TRAIT +707
#define SPECIES_PHANTUMP_SPECIAL_TRAIT +708
#define SPECIES_TREVENANT_SPECIAL_TRAIT +709
#define SPECIES_PUMPKABOO_SPECIAL_TRAIT +710
#define SPECIES_GOURGEIST_SPECIAL_TRAIT +711
#define SPECIES_BERGMITE_SPECIAL_TRAIT +712
#define SPECIES_AVALUGG_SPECIAL_TRAIT +713
#define SPECIES_NOIBAT_SPECIAL_TRAIT +714
#define SPECIES_NOIVERN_SPECIAL_TRAIT +715
#define SPECIES_XERNEAS_SPECIAL_TRAIT +716
#define SPECIES_YVELTAL_SPECIAL_TRAIT +717
#define SPECIES_ZYGARDE_SPECIAL_TRAIT +718
#define SPECIES_DIANCIE_SPECIAL_TRAIT +719
#define SPECIES_HOOPA_SPECIAL_TRAIT +720
#define SPECIES_VOLCANION_SPECIAL_TRAIT +721
#define SPECIES_ROWLET_SPECIAL_TRAIT +722
#define SPECIES_DARTRIX_SPECIAL_TRAIT +723
#define SPECIES_DECIDUEYE_SPECIAL_TRAIT +724
#define SPECIES_LITTEN_SPECIAL_TRAIT +725
#define SPECIES_TORRACAT_SPECIAL_TRAIT +726
#define SPECIES_INCINEROAR_SPECIAL_TRAIT +727
#define SPECIES_POPPLIO_SPECIAL_TRAIT +728
#define SPECIES_BRIONNE_SPECIAL_TRAIT +729
#define SPECIES_PRIMARINA_SPECIAL_TRAIT +730
#define SPECIES_PIKIPEK_SPECIAL_TRAIT +731
#define SPECIES_TRUMBEAK_SPECIAL_TRAIT +732
#define SPECIES_TOUCANNON_SPECIAL_TRAIT +733
#define SPECIES_YUNGOOS_SPECIAL_TRAIT +734
#define SPECIES_GUMSHOOS_SPECIAL_TRAIT +735
#define SPECIES_GRUBBIN_SPECIAL_TRAIT +736
#define SPECIES_CHARJABUG_SPECIAL_TRAIT +737
#define SPECIES_VIKAVOLT_SPECIAL_TRAIT +738
#define SPECIES_CRABRAWLER_SPECIAL_TRAIT +739
#define SPECIES_CRABOMINABLE_SPECIAL_TRAIT +740
#define SPECIES_ORICORIO_SPECIAL_TRAIT +741
#define SPECIES_CUTIEFLY_SPECIAL_TRAIT +742
#define SPECIES_RIBOMBEE_SPECIAL_TRAIT +743
#define SPECIES_ROCKRUFF_SPECIAL_TRAIT +744
#define SPECIES_LYCANROC_SPECIAL_TRAIT +745
#define SPECIES_WISHIWASHI_SPECIAL_TRAIT +746
#define SPECIES_MAREANIE_SPECIAL_TRAIT +747
#define SPECIES_TOXAPEX_SPECIAL_TRAIT +748
#define SPECIES_MUDBRAY_SPECIAL_TRAIT +749
#define SPECIES_MUDSDALE_SPECIAL_TRAIT +750
#define SPECIES_DEWPIDER_SPECIAL_TRAIT +751
#define SPECIES_ARAQUANID_SPECIAL_TRAIT +752
#define SPECIES_FOMANTIS_SPECIAL_TRAIT +753
#define SPECIES_LURANTIS_SPECIAL_TRAIT +754
#define SPECIES_MORELULL_SPECIAL_TRAIT +755
#define SPECIES_SHIINOTIC_SPECIAL_TRAIT +756
#define SPECIES_SALANDIT_SPECIAL_TRAIT +757
#define SPECIES_SALAZZLE_SPECIAL_TRAIT +758
#define SPECIES_STUFFUL_SPECIAL_TRAIT +759
#define SPECIES_BEWEAR_SPECIAL_TRAIT +760
#define SPECIES_BOUNSWEET_SPECIAL_TRAIT +761
#define SPECIES_STEENEE_SPECIAL_TRAIT +762
#define SPECIES_TSAREENA_SPECIAL_TRAIT +763
#define SPECIES_COMFEY_SPECIAL_TRAIT +764
#define SPECIES_ORANGURU_SPECIAL_TRAIT +765
#define SPECIES_PASSIMIAN_SPECIAL_TRAIT +766
#define SPECIES_WIMPOD_SPECIAL_TRAIT +767
#define SPECIES_GOLISOPOD_SPECIAL_TRAIT +768
#define SPECIES_SANDYGAST_SPECIAL_TRAIT +769
#define SPECIES_PALOSSAND_SPECIAL_TRAIT +770
#define SPECIES_PYUKUMUKU_SPECIAL_TRAIT +771
#define SPECIES_TYPE_NULL_SPECIAL_TRAIT +772
#define SPECIES_SILVALLY_SPECIAL_TRAIT +773
#define SPECIES_MINIOR_SPECIAL_TRAIT +774
#define SPECIES_KOMALA_SPECIAL_TRAIT +775
#define SPECIES_TURTONATOR_SPECIAL_TRAIT +776
#define SPECIES_TOGEDEMARU_SPECIAL_TRAIT +777
#define SPECIES_MIMIKYU_SPECIAL_TRAIT +778
#define SPECIES_BRUXISH_SPECIAL_TRAIT +779
#define SPECIES_DRAMPA_SPECIAL_TRAIT +780
#define SPECIES_DHELMISE_SPECIAL_TRAIT +781
#define SPECIES_JANGMO_O_SPECIAL_TRAIT +782
#define SPECIES_HAKAMO_O_SPECIAL_TRAIT +783
#define SPECIES_KOMMO_O_SPECIAL_TRAIT +784
#define SPECIES_TAPU_KOKO_SPECIAL_TRAIT +785
#define SPECIES_TAPU_LELE_SPECIAL_TRAIT +786
#define SPECIES_TAPU_BULU_SPECIAL_TRAIT +787
#define SPECIES_TAPU_FINI_SPECIAL_TRAIT +788
#define SPECIES_COSMOG_SPECIAL_TRAIT +789
#define SPECIES_COSMOEM_SPECIAL_TRAIT +790
#define SPECIES_SOLGALEO_SPECIAL_TRAIT +791
#define SPECIES_LUNALA_SPECIAL_TRAIT +792
#define SPECIES_NIHILEGO_SPECIAL_TRAIT +793
#define SPECIES_BUZZWOLE_SPECIAL_TRAIT +794
#define SPECIES_PHEROMOSA_SPECIAL_TRAIT +795
#define SPECIES_XURKITREE_SPECIAL_TRAIT +796
#define SPECIES_CELESTEELA_SPECIAL_TRAIT +797
#define SPECIES_KARTANA_SPECIAL_TRAIT +798
#define SPECIES_GUZZLORD_SPECIAL_TRAIT +799
#define SPECIES_NECROZMA_SPECIAL_TRAIT +800
#define SPECIES_MAGEARNA_SPECIAL_TRAIT +801
#define SPECIES_MARSHADOW_SPECIAL_TRAIT +802
#define SPECIES_POIPOLE_SPECIAL_TRAIT +803
#define SPECIES_NAGANADEL_SPECIAL_TRAIT +804
#define SPECIES_STAKATAKA_SPECIAL_TRAIT +805
#define SPECIES_BLACEPHALON_SPECIAL_TRAIT +806
#define SPECIES_ZERAORA_SPECIAL_TRAIT +807
#define SPECIES_MELTAN_SPECIAL_TRAIT +808
#define SPECIES_MELMETAL_SPECIAL_TRAIT +809
#define SPECIES_GROOKEY_SPECIAL_TRAIT +810
#define SPECIES_THWACKEY_SPECIAL_TRAIT +811
#define SPECIES_RILLABOOM_SPECIAL_TRAIT +812
#define SPECIES_SCORBUNNY_SPECIAL_TRAIT +813
#define SPECIES_RABOOT_SPECIAL_TRAIT +814
#define SPECIES_CINDERACE_SPECIAL_TRAIT +815
#define SPECIES_SOBBLE_SPECIAL_TRAIT +816
#define SPECIES_DRIZZILE_SPECIAL_TRAIT +817
#define SPECIES_INTELEON_SPECIAL_TRAIT +818
#define SPECIES_SKWOVET_SPECIAL_TRAIT +819
#define SPECIES_GREEDENT_SPECIAL_TRAIT +820
#define SPECIES_ROOKIDEE_SPECIAL_TRAIT +821
#define SPECIES_CORVISQUIRE_SPECIAL_TRAIT +822
#define SPECIES_CORVIKNIGHT_SPECIAL_TRAIT +823
#define SPECIES_BLIPBUG_SPECIAL_TRAIT +824
#define SPECIES_DOTTLER_SPECIAL_TRAIT +825
#define SPECIES_ORBEETLE_SPECIAL_TRAIT +826
#define SPECIES_NICKIT_SPECIAL_TRAIT +827
#define SPECIES_THIEVUL_SPECIAL_TRAIT +828
#define SPECIES_GOSSIFLEUR_SPECIAL_TRAIT +829
#define SPECIES_ELDEGOSS_SPECIAL_TRAIT +830
#define SPECIES_WOOLOO_SPECIAL_TRAIT +831
#define SPECIES_DUBWOOL_SPECIAL_TRAIT +832
#define SPECIES_CHEWTLE_SPECIAL_TRAIT +833
#define SPECIES_DREDNAW_SPECIAL_TRAIT +834
#define SPECIES_YAMPER_SPECIAL_TRAIT +835
#define SPECIES_BOLTUND_SPECIAL_TRAIT +836
#define SPECIES_ROLYCOLY_SPECIAL_TRAIT +837
#define SPECIES_CARKOL_SPECIAL_TRAIT +838
#define SPECIES_COALOSSAL_SPECIAL_TRAIT +839
#define SPECIES_APPLIN_SPECIAL_TRAIT +840
#define SPECIES_FLAPPLE_SPECIAL_TRAIT +841
#define SPECIES_APPLETUN_SPECIAL_TRAIT +842
#define SPECIES_SILICOBRA_SPECIAL_TRAIT +843
#define SPECIES_SANDACONDA_SPECIAL_TRAIT +844
#define SPECIES_CRAMORANT_SPECIAL_TRAIT +845
#define SPECIES_ARROKUDA_SPECIAL_TRAIT +846
#define SPECIES_BARRASKEWDA_SPECIAL_TRAIT +847
#define SPECIES_TOXEL_SPECIAL_TRAIT +848
#define SPECIES_TOXTRICITY_SPECIAL_TRAIT +849
#define SPECIES_SIZZLIPEDE_SPECIAL_TRAIT +850
#define SPECIES_CENTISKORCH_SPECIAL_TRAIT +851
#define SPECIES_CLOBBOPUS_SPECIAL_TRAIT +852
#define SPECIES_GRAPPLOCT_SPECIAL_TRAIT +853
#define SPECIES_SINISTEA_SPECIAL_TRAIT +854
#define SPECIES_POLTEAGEIST_SPECIAL_TRAIT +855
#define SPECIES_HATENNA_SPECIAL_TRAIT +856
#define SPECIES_HATTREM_SPECIAL_TRAIT +857
#define SPECIES_HATTERENE_SPECIAL_TRAIT +858
#define SPECIES_IMPIDIMP_SPECIAL_TRAIT +859
#define SPECIES_MORGREM_SPECIAL_TRAIT +860
#define SPECIES_GRIMMSNARL_SPECIAL_TRAIT +861
#define SPECIES_OBSTAGOON_SPECIAL_TRAIT +862
#define SPECIES_PERRSERKER_SPECIAL_TRAIT +863
#define SPECIES_CURSOLA_SPECIAL_TRAIT +864
#define SPECIES_SIRFETCHD_SPECIAL_TRAIT +865
#define SPECIES_MR_RIME_SPECIAL_TRAIT +866
#define SPECIES_RUNERIGUS_SPECIAL_TRAIT +867
#define SPECIES_MILCERY_SPECIAL_TRAIT +868
#define SPECIES_ALCREMIE_SPECIAL_TRAIT +869
#define SPECIES_FALINKS_SPECIAL_TRAIT +870
#define SPECIES_PINCURCHIN_SPECIAL_TRAIT +871
#define SPECIES_SNOM_SPECIAL_TRAIT +872
#define SPECIES_FROSMOTH_SPECIAL_TRAIT +873
#define SPECIES_STONJOURNER_SPECIAL_TRAIT +874
#define SPECIES_EISCUE_SPECIAL_TRAIT +875
#define SPECIES_INDEEDEE_SPECIAL_TRAIT +876
#define SPECIES_MORPEKO_SPECIAL_TRAIT +877
#define SPECIES_CUFANT_SPECIAL_TRAIT +878
#define SPECIES_COPPERAJAH_SPECIAL_TRAIT +879
#define SPECIES_DRACOZOLT_SPECIAL_TRAIT +880
#define SPECIES_ARCTOZOLT_SPECIAL_TRAIT +881
#define SPECIES_DRACOVISH_SPECIAL_TRAIT +882
#define SPECIES_ARCTOVISH_SPECIAL_TRAIT +883
#define SPECIES_DURALUDON_SPECIAL_TRAIT +884
#define SPECIES_DREEPY_SPECIAL_TRAIT +885
#define SPECIES_DRAKLOAK_SPECIAL_TRAIT +886
#define SPECIES_DRAGAPULT_SPECIAL_TRAIT +887
#define SPECIES_ZACIAN_SPECIAL_TRAIT +888
#define SPECIES_ZAMAZENTA_SPECIAL_TRAIT +889
#define SPECIES_ETERNATUS_SPECIAL_TRAIT +890
#define SPECIES_KUBFU_SPECIAL_TRAIT +891
#define SPECIES_URSHIFU_SPECIAL_TRAIT +892
#define SPECIES_ZARUDE_SPECIAL_TRAIT +893
#define SPECIES_REGIELEKI_SPECIAL_TRAIT +894
#define SPECIES_REGIDRAGO_SPECIAL_TRAIT +895
#define SPECIES_GLASTRIER_SPECIAL_TRAIT +896
#define SPECIES_SPECTRIER_SPECIAL_TRAIT +897
#define SPECIES_CALYREX_SPECIAL_TRAIT +898
#define SPECIES_WYRDEER_SPECIAL_TRAIT +899
#define SPECIES_KLEAVOR_SPECIAL_TRAIT +900
#define SPECIES_URSALUNA_SPECIAL_TRAIT +901
#define SPECIES_BASCULEGION_SPECIAL_TRAIT +902
#define SPECIES_SNEASLER_SPECIAL_TRAIT +903
#define SPECIES_OVERQWIL_SPECIAL_TRAIT +904
#define SPECIES_ENAMORUS_SPECIAL_TRAIT +905

#define NUM_SPECIES SPECIES_EGG

#endif  // GUARD_CONSTANTS_SPECIES_H
